/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.AnyVcsRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnyVcsRepositoryValidator {
	boolean validate();

	boolean validatePluginKey(String value);

	boolean validateServerConfig(EMap<String, String> value);

	boolean validateBranchConfig(EMap<String, String> value);
}
