/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.BitbucketServerRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BitbucketServerRepositoryValidator {
	boolean validate();

	boolean validateServer(String value);

	boolean validateProject(String value);

	boolean validateSlug(String value);

	boolean validateCloneUrl(String value);

	boolean validatePublicKey(String value);

	boolean validatePrivateKey(String value);

	boolean validateBranch(String value);

	boolean validateLfs(Boolean value);

	boolean validateUseShallowClones(Boolean value);

	boolean validateSubmodules(Boolean value);

	boolean validateCommandTimeoutMinutes(Integer value);

	boolean validateFetchAll(Boolean value);
}
