/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.BranchSpecificConfig;
import com.mddoai.metamodel.bambooMM.DockerConfig;
import com.mddoai.metamodel.bambooMM.Job;
import com.mddoai.metamodel.bambooMM.Label;
import com.mddoai.metamodel.bambooMM.Notification;
import com.mddoai.metamodel.bambooMM.Stage;
import com.mddoai.metamodel.bambooMM.Trigger;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.BranchOverride}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchOverrideValidator {
	boolean validate();

	boolean validateBranchPattern(String value);

	boolean validateStages(EList<Stage> value);

	boolean validateJobs(EList<Job> value);

	boolean validateTriggers(EList<Trigger> value);

	boolean validateNotifications(EList<Notification> value);

	boolean validateVariables(EMap<String, String> value);

	boolean validateLabels(EList<Label> value);

	boolean validateDocker(DockerConfig value);

	boolean validateBranchConfig(BranchSpecificConfig value);
}
