/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.BRANCH_CREATE_STRATEGY;
import com.mddoai.metamodel.bambooMM.BranchDelete;
import com.mddoai.metamodel.bambooMM.BranchIntegration;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.BranchManagement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchManagementValidator {
	boolean validate();

	boolean validateCreate(BRANCH_CREATE_STRATEGY value);

	boolean validateCreatePattern(String value);

	boolean validateAcceptFork(Boolean value);

	boolean validateDelete(BranchDelete value);

	boolean validateIntegration(BranchIntegration value);

	boolean validateLinkToJira(Boolean value);
}
