/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.BranchIntegration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchIntegrationValidator {
	boolean validate();

	boolean validateMergeFrom(String value);

	boolean validateMergeTo(String value);

	boolean validatePushOnSuccess(boolean value);
}
