/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.FILE_FILTER_TYPE;
import com.mddoai.metamodel.bambooMM.QuietPeriod;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.ChangeDetection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChangeDetectionValidator {
	boolean validate();

	boolean validateQuietPeriod(QuietPeriod value);

	boolean validateExcludeChangesetPattern(String value);

	boolean validateFileFilterType(FILE_FILTER_TYPE value);

	boolean validateFileFilterPattern(String value);
}
