/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.CheckoutTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CheckoutTaskValidator {
	boolean validate();

	boolean validateRepository(String value);

	boolean validatePath(String value);

	boolean validateForceCleanBuild(Boolean value);

	boolean validateDefaultRepository(boolean value);
}
