/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.BLOCK_STRATEGY;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.Dependencies}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DependenciesValidator {
	boolean validate();

	boolean validateRequireAllStagesPassing(boolean value);

	boolean validateEnabledForBranches(boolean value);

	boolean validateBlockStrategy(BLOCK_STRATEGY value);

	boolean validatePlans(EList<String> value);
}
