/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.DeploymentPermissionEntry;
import com.mddoai.metamodel.bambooMM.Environment;
import com.mddoai.metamodel.bambooMM.EnvironmentPermissionEntry;
import com.mddoai.metamodel.bambooMM.NamedEnvironmentPermission;
import com.mddoai.metamodel.bambooMM.ReleaseNaming;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.DeploymentProject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentProjectValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateSourcePlan(String value);

	boolean validateServerName(String value);

	boolean validateReleaseNaming(ReleaseNaming value);

	boolean validateEnvironments(EList<Environment> value);

	boolean validatePermissions(EList<DeploymentPermissionEntry> value);

	boolean validateDefaultEnvironmentPermissions(EList<EnvironmentPermissionEntry> value);

	boolean validateEnvironmentPermissions(EList<NamedEnvironmentPermission> value);
}
