/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.DockerConfig}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DockerConfigValidator {
	boolean validate();

	boolean validateImage(String value);

	boolean validateVolumes(EMap<String, String> value);

	boolean validateUseDefaultVolumes(boolean value);

	boolean validateDockerRunArguments(EList<String> value);
}
