/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.ChangeDetection;
import com.mddoai.metamodel.bambooMM.REPOSITORY_SCOPE;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.GitRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GitRepositoryValidator {
	boolean validate();

	boolean validateUrl(String value);

	boolean validateBranch(String value);

	boolean validateUsername(String value);

	boolean validatePassword(String value);

	boolean validateSshKey(String value);

	boolean validateSshKeyPassphrase(String value);

	boolean validateSharedCredentials(String value);

	boolean validateSharedCredentialsScope(REPOSITORY_SCOPE value);

	boolean validateLfs(Boolean value);

	boolean validateUseShallowClones(Boolean value);

	boolean validateSubmodules(Boolean value);

	boolean validateFetchAll(Boolean value);

	boolean validateCacheOnAgents(Boolean value);

	boolean validateVerboseLogs(Boolean value);

	boolean validateCommandTimeoutMinutes(Integer value);

	boolean validateChangeDetection(ChangeDetection value);
}
