/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.VARIABLE_SCOPE;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.InjectVariablesTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InjectVariablesTaskValidator {
	boolean validate();

	boolean validateFile(String value);

	boolean validateScope(VARIABLE_SCOPE value);

	boolean validateNamespace(String value);
}
