/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.Artifact;
import com.mddoai.metamodel.bambooMM.ArtifactSubscription;
import com.mddoai.metamodel.bambooMM.DockerConfig;
import com.mddoai.metamodel.bambooMM.OtherConfig;
import com.mddoai.metamodel.bambooMM.Requirement;
import com.mddoai.metamodel.bambooMM.Task;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.Job}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JobValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateKey(String value);

	boolean validateTasks(EList<Task> value);

	boolean validateFinalTasks(EList<Task> value);

	boolean validateArtifacts(EList<Artifact> value);

	boolean validateArtifactSubscriptions(EList<ArtifactSubscription> value);

	boolean validateRequirements(EList<Requirement> value);

	boolean validateVariables(EMap<String, String> value);

	boolean validateDocker(DockerConfig value);

	boolean validateOther(OtherConfig value);
}
