/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.MavenTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MavenTaskValidator {
	boolean validate();

	boolean validateExecutable(String value);

	boolean validateJdk(String value);

	boolean validateGoal(String value);

	boolean validateTests(String value);

	boolean validateEnvironment(String value);

	boolean validateWorkingDir(String value);

	boolean validateProjectFile(String value);

	boolean validateUseReturnCode(Boolean value);
}
