/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.EnvironmentPermissionEntry;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.NamedEnvironmentPermission}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NamedEnvironmentPermissionValidator {
	boolean validate();

	boolean validateEnvironmentName(String value);

	boolean validateEntries(EList<EnvironmentPermissionEntry> value);
}
