/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.NOTIFICATION_EVENT_TYPE;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.NotificationEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NotificationEventValidator {
	boolean validate();

	boolean validateType(NOTIFICATION_EVENT_TYPE value);

	boolean validateFailures(Integer value);

	boolean validateFirstOnly(Boolean value);
}
