/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.NotificationEvent;
import com.mddoai.metamodel.bambooMM.NotificationRecipient;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.Notification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NotificationValidator {
	boolean validate();

	boolean validateRecipients(EList<NotificationRecipient> value);

	boolean validateEvents(EList<NotificationEvent> value);
}
