/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.PERMISSION_ROLE;
import com.mddoai.metamodel.bambooMM.PERMISSION_TYPE;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.PermissionEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PermissionEntryValidator {
	boolean validate();

	boolean validateUsers(EList<String> value);

	boolean validateGroups(EList<String> value);

	boolean validateRoles(EList<PERMISSION_ROLE> value);

	boolean validatePermissions(EList<PERMISSION_TYPE> value);
}
