/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.BranchManagement;
import com.mddoai.metamodel.bambooMM.BranchOverride;
import com.mddoai.metamodel.bambooMM.Dependencies;
import com.mddoai.metamodel.bambooMM.DockerConfig;
import com.mddoai.metamodel.bambooMM.Job;
import com.mddoai.metamodel.bambooMM.Label;
import com.mddoai.metamodel.bambooMM.Notification;
import com.mddoai.metamodel.bambooMM.OtherConfig;
import com.mddoai.metamodel.bambooMM.PlanPermissionEntry;
import com.mddoai.metamodel.bambooMM.Repository;
import com.mddoai.metamodel.bambooMM.Stage;
import com.mddoai.metamodel.bambooMM.Trigger;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.Plan}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlanValidator {
	boolean validate();

	boolean validateProjectKey(String value);

	boolean validateKey(String value);

	boolean validateName(String value);

	boolean validateServerName(String value);

	boolean validateStages(EList<Stage> value);

	boolean validateJobs(EList<Job> value);

	boolean validateTriggers(EList<Trigger> value);

	boolean validateRepositories(EList<Repository> value);

	boolean validateVariables(EMap<String, String> value);

	boolean validateNotifications(EList<Notification> value);

	boolean validateLabels(EList<Label> value);

	boolean validateBranches(BranchManagement value);

	boolean validateDependencies(Dependencies value);

	boolean validateDocker(DockerConfig value);

	boolean validateBranchOverrides(EList<BranchOverride> value);

	boolean validateOther(OtherConfig value);

	boolean validatePermissions(EList<PlanPermissionEntry> value);
}
