/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.NOTIFICATION_ROLE;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.RoleRecipient}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoleRecipientValidator {
	boolean validate();

	boolean validateRole(NOTIFICATION_ROLE value);
}
