/**
 *
 * $Id$
 */
package com.mddoai.metamodel.bambooMM.validation;

import com.mddoai.metamodel.bambooMM.TEST_PARSER_TYPE;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.bambooMM.TestParserTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestParserTaskValidator {
	boolean validate();

	boolean validateType(TEST_PARSER_TYPE value);

	boolean validateTestResults(EList<String> value);

	boolean validateIgnoreTime(Boolean value);
}
