<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="genericCICDMM" nsURI="http://www.mddoai.com/mddoai/metamodel/genericcicd"
    nsPrefix="genericCICDMM">
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentVariables" upperBound="-1"
        eType="#//VariableAssignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" lowerBound="1" upperBound="-1"
        eType="#//Job" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" eType="#//Agent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentVariables" upperBound="-1"
        eType="#//VariableAssignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategy" eType="#//Matrix"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//AbstractStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStep" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentVariables" upperBound="-1"
        eType="#//VariableAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandStep" eSuperTypes="#//AbstractStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CliParsingAndEnvironmentInitStep" eSuperTypes="#//AbstractStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" lowerBound="1" eType="#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Secret" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignment" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//VariableDeclaration"/>
  </eClassifiers>
</ecore:EPackage>