#

pluginName = com.mddoai.metamodel.azuredevops Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Pipeline_type = Pipeline
_UI_Extends_type = Extends
_UI_StageElement_type = Stage Element
_UI_Stage_type = Stage
_UI_StageTemplate_type = Stage Template
_UI_JobElement_type = Job Element
_UI_Job_type = Job
_UI_DeploymentJob_type = Deployment Job
_UI_JobTemplate_type = Job Template
_UI_Environment_type = Environment
_UI_DeploymentStrategy_type = Deployment Strategy
_UI_RunOnceStrategy_type = Run Once Strategy
_UI_RollingStrategy_type = Rolling Strategy
_UI_CanaryStrategy_type = Canary Strategy
_UI_DeployHook_type = Deploy Hook
_UI_OnSuccessOrFailureHook_type = On Success Or Failure Hook
_UI_JobStrategy_type = Job Strategy
_UI_MatrixEntry_type = Matrix Entry
_UI_MatrixVariable_type = Matrix Variable
_UI_JobUses_type = Job Uses
_UI_Pool_type = Pool
_UI_Workspace_type = Workspace
_UI_ContainerReference_type = Container Reference
_UI_ContainerAlias_type = Container Alias
_UI_ContainerImage_type = Container Image
_UI_MountReadOnly_type = Mount Read Only
_UI_ServiceEntry_type = Service Entry
_UI_Step_type = Step
_UI_TaskStep_type = Task Step
_UI_ScriptStep_type = Script Step
_UI_BashStep_type = Bash Step
_UI_PowershellStep_type = Powershell Step
_UI_PwshStep_type = Pwsh Step
_UI_CheckoutStep_type = Checkout Step
_UI_DownloadStep_type = Download Step
_UI_DownloadBuildStep_type = Download Build Step
_UI_GetPackageStep_type = Get Package Step
_UI_PublishStep_type = Publish Step
_UI_ReviewAppStep_type = Review App Step
_UI_StepTemplate_type = Step Template
_UI_StepTarget_type = Step Target
_UI_SettableVariables_type = Settable Variables
_UI_Trigger_type = Trigger
_UI_PrTrigger_type = Pr Trigger
_UI_CronSchedule_type = Cron Schedule
_UI_IncludeExcludeFilters_type = Include Exclude Filters
_UI_Parameter_type = Parameter
_UI_TemplateParameterAssignment_type = Template Parameter Assignment
_UI_VariableDefinition_type = Variable Definition
_UI_VariableName_type = Variable Name
_UI_VariableGroup_type = Variable Group
_UI_VariableTemplate_type = Variable Template
_UI_Resources_type = Resources
_UI_BuildResource_type = Build Resource
_UI_ContainerResource_type = Container Resource
_UI_ContainerResourceTrigger_type = Container Resource Trigger
_UI_PipelineResource_type = Pipeline Resource
_UI_PipelineResourceTrigger_type = Pipeline Resource Trigger
_UI_RepositoryResource_type = Repository Resource
_UI_WebhookResource_type = Webhook Resource
_UI_WebhookFilter_type = Webhook Filter
_UI_PackageResource_type = Package Resource
_UI_EnvEntry_type = Env Entry
_UI_InputEntry_type = Input Entry
_UI_TemplateContext_type = Template Context
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Pipeline_name_feature = Name
_UI_Pipeline_appendCommitMessageToRunName_feature = Append Commit Message To Run Name
_UI_Pipeline_lockBehavior_feature = Lock Behavior
_UI_Pipeline_trigger_feature = Trigger
_UI_Pipeline_pr_feature = Pr
_UI_Pipeline_schedules_feature = Schedules
_UI_Pipeline_parameters_feature = Parameters
_UI_Pipeline_variables_feature = Variables
_UI_Pipeline_pool_feature = Pool
_UI_Pipeline_resources_feature = Resources
_UI_Pipeline_stages_feature = Stages
_UI_Pipeline_jobs_feature = Jobs
_UI_Pipeline_steps_feature = Steps
_UI_Pipeline_extends_feature = Extends
_UI_Pipeline_workspace_feature = Workspace
_UI_Extends_template_feature = Template
_UI_Extends_parameters_feature = Parameters
_UI_Stage_stage_feature = Stage
_UI_Stage_displayName_feature = Display Name
_UI_Stage_condition_feature = Condition
_UI_Stage_lockBehavior_feature = Lock Behavior
_UI_Stage_trigger_feature = Trigger
_UI_Stage_isSkippable_feature = Is Skippable
_UI_Stage_dependsOn_feature = Depends On
_UI_Stage_pool_feature = Pool
_UI_Stage_variables_feature = Variables
_UI_Stage_jobs_feature = Jobs
_UI_Stage_templateContext_feature = Template Context
_UI_StageTemplate_template_feature = Template
_UI_StageTemplate_parameters_feature = Parameters
_UI_Job_job_feature = Job
_UI_Job_displayName_feature = Display Name
_UI_Job_condition_feature = Condition
_UI_Job_continueOnError_feature = Continue On Error
_UI_Job_timeoutInMinutes_feature = Timeout In Minutes
_UI_Job_cancelTimeoutInMinutes_feature = Cancel Timeout In Minutes
_UI_Job_dependsOn_feature = Depends On
_UI_Job_pool_feature = Pool
_UI_Job_variables_feature = Variables
_UI_Job_strategy_feature = Strategy
_UI_Job_container_feature = Container
_UI_Job_services_feature = Services
_UI_Job_workspace_feature = Workspace
_UI_Job_uses_feature = Uses
_UI_Job_steps_feature = Steps
_UI_Job_templateContext_feature = Template Context
_UI_DeploymentJob_deployment_feature = Deployment
_UI_DeploymentJob_displayName_feature = Display Name
_UI_DeploymentJob_condition_feature = Condition
_UI_DeploymentJob_continueOnError_feature = Continue On Error
_UI_DeploymentJob_timeoutInMinutes_feature = Timeout In Minutes
_UI_DeploymentJob_cancelTimeoutInMinutes_feature = Cancel Timeout In Minutes
_UI_DeploymentJob_dependsOn_feature = Depends On
_UI_DeploymentJob_pool_feature = Pool
_UI_DeploymentJob_variables_feature = Variables
_UI_DeploymentJob_environment_feature = Environment
_UI_DeploymentJob_strategy_feature = Strategy
_UI_DeploymentJob_container_feature = Container
_UI_DeploymentJob_services_feature = Services
_UI_DeploymentJob_workspace_feature = Workspace
_UI_DeploymentJob_uses_feature = Uses
_UI_DeploymentJob_templateContext_feature = Template Context
_UI_JobTemplate_template_feature = Template
_UI_JobTemplate_parameters_feature = Parameters
_UI_Environment_name_feature = Name
_UI_Environment_resourceName_feature = Resource Name
_UI_Environment_resourceId_feature = Resource Id
_UI_Environment_resourceType_feature = Resource Type
_UI_Environment_tags_feature = Tags
_UI_DeploymentStrategy_runOnce_feature = Run Once
_UI_DeploymentStrategy_rolling_feature = Rolling
_UI_DeploymentStrategy_canary_feature = Canary
_UI_RunOnceStrategy_preDeploy_feature = Pre Deploy
_UI_RunOnceStrategy_deploy_feature = Deploy
_UI_RunOnceStrategy_routeTraffic_feature = Route Traffic
_UI_RunOnceStrategy_postRouteTraffic_feature = Post Route Traffic
_UI_RunOnceStrategy_on_feature = On
_UI_RollingStrategy_maxParallel_feature = Max Parallel
_UI_RollingStrategy_preDeploy_feature = Pre Deploy
_UI_RollingStrategy_deploy_feature = Deploy
_UI_RollingStrategy_routeTraffic_feature = Route Traffic
_UI_RollingStrategy_postRouteTraffic_feature = Post Route Traffic
_UI_RollingStrategy_on_feature = On
_UI_CanaryStrategy_increments_feature = Increments
_UI_CanaryStrategy_preDeploy_feature = Pre Deploy
_UI_CanaryStrategy_deploy_feature = Deploy
_UI_CanaryStrategy_routeTraffic_feature = Route Traffic
_UI_CanaryStrategy_postRouteTraffic_feature = Post Route Traffic
_UI_CanaryStrategy_on_feature = On
_UI_DeployHook_pool_feature = Pool
_UI_DeployHook_steps_feature = Steps
_UI_OnSuccessOrFailureHook_failure_feature = Failure
_UI_OnSuccessOrFailureHook_success_feature = Success
_UI_JobStrategy_parallel_feature = Parallel
_UI_JobStrategy_maxParallel_feature = Max Parallel
_UI_JobStrategy_matrix_feature = Matrix
_UI_MatrixEntry_key_feature = Key
_UI_MatrixEntry_value_feature = Value
_UI_MatrixVariable_key_feature = Key
_UI_MatrixVariable_value_feature = Value
_UI_JobUses_repositories_feature = Repositories
_UI_JobUses_pools_feature = Pools
_UI_Pool_name_feature = Name
_UI_Pool_vmImage_feature = Vm Image
_UI_Pool_demands_feature = Demands
_UI_Workspace_clean_feature = Clean
_UI_ContainerAlias_alias_feature = Alias
_UI_ContainerImage_image_feature = Image
_UI_ContainerImage_endpoint_feature = Endpoint
_UI_ContainerImage_options_feature = Options
_UI_ContainerImage_ports_feature = Ports
_UI_ContainerImage_volumes_feature = Volumes
_UI_ContainerImage_mapDockerSocket_feature = Map Docker Socket
_UI_ContainerImage_env_feature = Env
_UI_ContainerImage_mountReadOnly_feature = Mount Read Only
_UI_MountReadOnly_work_feature = Work
_UI_MountReadOnly_externals_feature = Externals
_UI_MountReadOnly_tools_feature = Tools
_UI_MountReadOnly_tasks_feature = Tasks
_UI_ServiceEntry_key_feature = Key
_UI_ServiceEntry_value_feature = Value
_UI_Step_name_feature = Name
_UI_Step_displayName_feature = Display Name
_UI_Step_condition_feature = Condition
_UI_Step_continueOnError_feature = Continue On Error
_UI_Step_enabled_feature = Enabled
_UI_Step_timeoutInMinutes_feature = Timeout In Minutes
_UI_Step_retryCountOnTaskFailure_feature = Retry Count On Task Failure
_UI_Step_env_feature = Env
_UI_Step_target_feature = Target
_UI_TaskStep_task_feature = Task
_UI_TaskStep_inputs_feature = Inputs
_UI_ScriptStep_script_feature = Script
_UI_ScriptStep_failOnStderr_feature = Fail On Stderr
_UI_ScriptStep_workingDirectory_feature = Working Directory
_UI_BashStep_bash_feature = Bash
_UI_BashStep_failOnStderr_feature = Fail On Stderr
_UI_BashStep_workingDirectory_feature = Working Directory
_UI_PowershellStep_powershell_feature = Powershell
_UI_PowershellStep_errorActionPreference_feature = Error Action Preference
_UI_PowershellStep_failOnStderr_feature = Fail On Stderr
_UI_PowershellStep_ignoreLASTEXITCODE_feature = Ignore LASTEXITCODE
_UI_PowershellStep_workingDirectory_feature = Working Directory
_UI_PwshStep_pwsh_feature = Pwsh
_UI_PwshStep_errorActionPreference_feature = Error Action Preference
_UI_PwshStep_failOnStderr_feature = Fail On Stderr
_UI_PwshStep_ignoreLASTEXITCODE_feature = Ignore LASTEXITCODE
_UI_PwshStep_workingDirectory_feature = Working Directory
_UI_CheckoutStep_checkout_feature = Checkout
_UI_CheckoutStep_clean_feature = Clean
_UI_CheckoutStep_fetchDepth_feature = Fetch Depth
_UI_CheckoutStep_fetchFilter_feature = Fetch Filter
_UI_CheckoutStep_fetchTags_feature = Fetch Tags
_UI_CheckoutStep_lfs_feature = Lfs
_UI_CheckoutStep_persistCredentials_feature = Persist Credentials
_UI_CheckoutStep_submodules_feature = Submodules
_UI_CheckoutStep_path_feature = Path
_UI_CheckoutStep_sparseCheckoutDirectories_feature = Sparse Checkout Directories
_UI_CheckoutStep_sparseCheckoutPatterns_feature = Sparse Checkout Patterns
_UI_CheckoutStep_workspaceRepo_feature = Workspace Repo
_UI_DownloadStep_download_feature = Download
_UI_DownloadStep_artifact_feature = Artifact
_UI_DownloadStep_patterns_feature = Patterns
_UI_DownloadBuildStep_downloadBuild_feature = Download Build
_UI_DownloadBuildStep_artifact_feature = Artifact
_UI_DownloadBuildStep_path_feature = Path
_UI_DownloadBuildStep_patterns_feature = Patterns
_UI_GetPackageStep_getPackage_feature = Get Package
_UI_GetPackageStep_path_feature = Path
_UI_PublishStep_publish_feature = Publish
_UI_PublishStep_artifact_feature = Artifact
_UI_ReviewAppStep_reviewApp_feature = Review App
_UI_StepTemplate_template_feature = Template
_UI_StepTemplate_parameters_feature = Parameters
_UI_StepTarget_container_feature = Container
_UI_StepTarget_commands_feature = Commands
_UI_StepTarget_settableVariables_feature = Settable Variables
_UI_SettableVariables_none_feature = None
_UI_SettableVariables_variables_feature = Variables
_UI_Trigger_disabled_feature = Disabled
_UI_Trigger_batch_feature = Batch
_UI_Trigger_branchList_feature = Branch List
_UI_Trigger_branches_feature = Branches
_UI_Trigger_paths_feature = Paths
_UI_Trigger_tags_feature = Tags
_UI_PrTrigger_disabled_feature = Disabled
_UI_PrTrigger_autoCancel_feature = Auto Cancel
_UI_PrTrigger_drafts_feature = Drafts
_UI_PrTrigger_branchList_feature = Branch List
_UI_PrTrigger_branches_feature = Branches
_UI_PrTrigger_paths_feature = Paths
_UI_CronSchedule_cron_feature = Cron
_UI_CronSchedule_displayName_feature = Display Name
_UI_CronSchedule_batch_feature = Batch
_UI_CronSchedule_always_feature = Always
_UI_CronSchedule_branches_feature = Branches
_UI_IncludeExcludeFilters_include_feature = Include
_UI_IncludeExcludeFilters_exclude_feature = Exclude
_UI_Parameter_name_feature = Name
_UI_Parameter_displayName_feature = Display Name
_UI_Parameter_type_feature = Type
_UI_Parameter_default_feature = Default
_UI_Parameter_values_feature = Values
_UI_TemplateParameterAssignment_key_feature = Key
_UI_TemplateParameterAssignment_value_feature = Value
_UI_VariableName_name_feature = Name
_UI_VariableName_value_feature = Value
_UI_VariableName_readonly_feature = Readonly
_UI_VariableGroup_group_feature = Group
_UI_VariableTemplate_template_feature = Template
_UI_VariableTemplate_parameters_feature = Parameters
_UI_Resources_builds_feature = Builds
_UI_Resources_containers_feature = Containers
_UI_Resources_pipelines_feature = Pipelines
_UI_Resources_repositories_feature = Repositories
_UI_Resources_webhooks_feature = Webhooks
_UI_Resources_packages_feature = Packages
_UI_BuildResource_build_feature = Build
_UI_BuildResource_type_feature = Type
_UI_BuildResource_connection_feature = Connection
_UI_BuildResource_source_feature = Source
_UI_BuildResource_version_feature = Version
_UI_BuildResource_branch_feature = Branch
_UI_BuildResource_trigger_feature = Trigger
_UI_ContainerResource_container_feature = Container
_UI_ContainerResource_image_feature = Image
_UI_ContainerResource_type_feature = Type
_UI_ContainerResource_azureSubscription_feature = Azure Subscription
_UI_ContainerResource_resourceGroup_feature = Resource Group
_UI_ContainerResource_registry_feature = Registry
_UI_ContainerResource_repository_feature = Repository
_UI_ContainerResource_endpoint_feature = Endpoint
_UI_ContainerResource_localImage_feature = Local Image
_UI_ContainerResource_options_feature = Options
_UI_ContainerResource_ports_feature = Ports
_UI_ContainerResource_volumes_feature = Volumes
_UI_ContainerResource_mapDockerSocket_feature = Map Docker Socket
_UI_ContainerResource_env_feature = Env
_UI_ContainerResource_mountReadOnly_feature = Mount Read Only
_UI_ContainerResource_trigger_feature = Trigger
_UI_ContainerResourceTrigger_enabled_feature = Enabled
_UI_ContainerResourceTrigger_disabled_feature = Disabled
_UI_ContainerResourceTrigger_tags_feature = Tags
_UI_PipelineResource_pipeline_feature = Pipeline
_UI_PipelineResource_project_feature = Project
_UI_PipelineResource_source_feature = Source
_UI_PipelineResource_version_feature = Version
_UI_PipelineResource_branch_feature = Branch
_UI_PipelineResource_tags_feature = Tags
_UI_PipelineResource_trigger_feature = Trigger
_UI_PipelineResourceTrigger_enabled_feature = Enabled
_UI_PipelineResourceTrigger_disabled_feature = Disabled
_UI_PipelineResourceTrigger_stages_feature = Stages
_UI_PipelineResourceTrigger_tags_feature = Tags
_UI_PipelineResourceTrigger_branches_feature = Branches
_UI_RepositoryResource_repository_feature = Repository
_UI_RepositoryResource_name_feature = Name
_UI_RepositoryResource_type_feature = Type
_UI_RepositoryResource_endpoint_feature = Endpoint
_UI_RepositoryResource_ref_feature = Ref
_UI_RepositoryResource_trigger_feature = Trigger
_UI_WebhookResource_webhook_feature = Webhook
_UI_WebhookResource_connection_feature = Connection
_UI_WebhookResource_type_feature = Type
_UI_WebhookResource_filters_feature = Filters
_UI_WebhookFilter_path_feature = Path
_UI_WebhookFilter_value_feature = Value
_UI_PackageResource_package_feature = Package
_UI_PackageResource_type_feature = Type
_UI_PackageResource_connection_feature = Connection
_UI_PackageResource_name_feature = Name
_UI_PackageResource_version_feature = Version
_UI_PackageResource_tag_feature = Tag
_UI_PackageResource_trigger_feature = Trigger
_UI_EnvEntry_key_feature = Key
_UI_EnvEntry_value_feature = Value
_UI_InputEntry_key_feature = Key
_UI_InputEntry_value_feature = Value
_UI_TemplateContext_properties_feature = Properties
_UI_Unknown_feature = Unspecified

_UI_LOCK_BEHAVIOR_sequential_literal = sequential
_UI_LOCK_BEHAVIOR_runLatest_literal = runLatest
_UI_STAGE_TRIGGER_manual_literal = manual
_UI_STAGE_TRIGGER_automatic_literal = automatic
_UI_WORKSPACE_CLEAN_outputs_literal = outputs
_UI_WORKSPACE_CLEAN_resources_literal = resources
_UI_WORKSPACE_CLEAN_all_literal = all
_UI_PARAMETER_TYPE_string_literal = string
_UI_PARAMETER_TYPE_number_literal = number
_UI_PARAMETER_TYPE_boolean_literal = boolean
_UI_PARAMETER_TYPE_object_literal = object
_UI_PARAMETER_TYPE_step_literal = step
_UI_PARAMETER_TYPE_stepList_literal = stepList
_UI_PARAMETER_TYPE_job_literal = job
_UI_PARAMETER_TYPE_jobList_literal = jobList
_UI_PARAMETER_TYPE_deployment_literal = deployment
_UI_PARAMETER_TYPE_deploymentList_literal = deploymentList
_UI_PARAMETER_TYPE_stage_literal = stage
_UI_PARAMETER_TYPE_stageList_literal = stageList
_UI_REPOSITORY_TYPE_git_literal = git
_UI_REPOSITORY_TYPE_github_literal = github
_UI_REPOSITORY_TYPE_githubenterprise_literal = githubenterprise
_UI_REPOSITORY_TYPE_bitbucket_literal = bitbucket
_UI_TARGET_COMMANDS_any_literal = any
_UI_TARGET_COMMANDS_restricted_literal = restricted
_UI_PackageResource_packageName_feature = Package Name
