/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.BuildResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BuildResourceValidator {
	boolean validate();

	boolean validateBuild(String value);

	boolean validateType(String value);

	boolean validateConnection(String value);

	boolean validateSource(String value);

	boolean validateVersion(String value);

	boolean validateBranch(String value);

	boolean validateTrigger(String value);
}
