/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.DeployHook;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.OnSuccessOrFailureHook;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CanaryStrategy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CanaryStrategyValidator {
	boolean validate();

	boolean validateIncrements(EList<String> value);

	boolean validatePreDeploy(DeployHook value);

	boolean validateDeploy(DeployHook value);

	boolean validateRouteTraffic(DeployHook value);

	boolean validatePostRouteTraffic(DeployHook value);

	boolean validateOn(OnSuccessOrFailureHook value);
}
