/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CheckoutStep}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CheckoutStepValidator {
	boolean validate();

	boolean validateCheckout(String value);

	boolean validateClean(String value);

	boolean validateFetchDepth(String value);

	boolean validateFetchFilter(String value);

	boolean validateFetchTags(String value);

	boolean validateLfs(String value);

	boolean validatePersistCredentials(String value);

	boolean validateSubmodules(String value);

	boolean validatePath(String value);

	boolean validateSparseCheckoutDirectories(String value);

	boolean validateSparseCheckoutPatterns(String value);

	boolean validateWorkspaceRepo(Boolean value);
}
