/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.MountReadOnly;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerImage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerImageValidator {
	boolean validate();

	boolean validateImage(String value);

	boolean validateEndpoint(String value);

	boolean validateOptions(String value);

	boolean validatePorts(EList<String> value);

	boolean validateVolumes(EList<String> value);

	boolean validateMapDockerSocket(Boolean value);

	boolean validateEnv(EMap<String, String> value);

	boolean validateMountReadOnly(MountReadOnly value);
}
