/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.IncludeExcludeFilters;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CronSchedule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CronScheduleValidator {
	boolean validate();

	boolean validateCron(String value);

	boolean validateDisplayName(String value);

	boolean validateBatch(Boolean value);

	boolean validateAlways(Boolean value);

	boolean validateBranches(IncludeExcludeFilters value);
}
