/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.CanaryStrategy;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.RollingStrategy;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.RunOnceStrategy;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeploymentStrategy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentStrategyValidator {
	boolean validate();

	boolean validateRunOnce(RunOnceStrategy value);

	boolean validateRolling(RollingStrategy value);

	boolean validateCanary(CanaryStrategy value);
}
