/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerReference;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.DeploymentStrategy;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Environment;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.JobUses;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Pool;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.TemplateContext;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableDefinition;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Workspace;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeploymentJob}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentJobValidator {
	boolean validate();

	boolean validateDeployment(String value);

	boolean validateDisplayName(String value);

	boolean validateCondition(String value);

	boolean validateContinueOnError(String value);

	boolean validateTimeoutInMinutes(String value);

	boolean validateCancelTimeoutInMinutes(String value);

	boolean validateDependsOn(EList<String> value);

	boolean validatePool(Pool value);

	boolean validateVariables(EList<VariableDefinition> value);

	boolean validateEnvironment(Environment value);

	boolean validateStrategy(DeploymentStrategy value);

	boolean validateContainer(ContainerReference value);

	boolean validateServices(EMap<String, String> value);

	boolean validateWorkspace(Workspace value);

	boolean validateUses(JobUses value);

	boolean validateTemplateContext(TemplateContext value);
}
