/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.IncludeExcludeFilters;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResourceTrigger}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PipelineResourceTriggerValidator {
	boolean validate();

	boolean validateEnabled(Boolean value);

	boolean validateDisabled(Boolean value);

	boolean validateStages(EList<String> value);

	boolean validateTags(EList<String> value);

	boolean validateBranches(IncludeExcludeFilters value);
}
