/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.CronSchedule;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Extends;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.JobElement;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.LOCK_BEHAVIOR;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Parameter;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Pool;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.PrTrigger;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Resources;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.StageElement;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Step;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Trigger;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableDefinition;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Workspace;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Pipeline}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PipelineValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateAppendCommitMessageToRunName(Boolean value);

	boolean validateLockBehavior(LOCK_BEHAVIOR value);

	boolean validateTrigger(Trigger value);

	boolean validatePr(PrTrigger value);

	boolean validateSchedules(EList<CronSchedule> value);

	boolean validateParameters(EList<Parameter> value);

	boolean validateVariables(EList<VariableDefinition> value);

	boolean validatePool(Pool value);

	boolean validateResources(Resources value);

	boolean validateStages(EList<StageElement> value);

	boolean validateJobs(EList<JobElement> value);

	boolean validateSteps(EList<Step> value);

	boolean validateExtends(Extends value);

	boolean validateWorkspace(Workspace value);
}
