/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResourceTrigger;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PipelineResourceValidator {
	boolean validate();

	boolean validatePipeline(String value);

	boolean validateProject(String value);

	boolean validateSource(String value);

	boolean validateVersion(String value);

	boolean validateBranch(String value);

	boolean validateTags(EList<String> value);

	boolean validateTrigger(PipelineResourceTrigger value);
}
