/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.REPOSITORY_TYPE;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Trigger;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.RepositoryResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RepositoryResourceValidator {
	boolean validate();

	boolean validateRepository(String value);

	boolean validateName(String value);

	boolean validateType(REPOSITORY_TYPE value);

	boolean validateEndpoint(String value);

	boolean validateRef(String value);

	boolean validateTrigger(Trigger value);
}
