/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.BuildResource;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerResource;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.PackageResource;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResource;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.RepositoryResource;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.WebhookResource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Resources}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourcesValidator {
	boolean validate();

	boolean validateBuilds(EList<BuildResource> value);

	boolean validateContainers(EList<ContainerResource> value);

	boolean validatePipelines(EList<PipelineResource> value);

	boolean validateRepositories(EList<RepositoryResource> value);

	boolean validateWebhooks(EList<WebhookResource> value);

	boolean validatePackages(EList<PackageResource> value);
}
