/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.JobElement;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.LOCK_BEHAVIOR;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.Pool;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.STAGE_TRIGGER;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.TemplateContext;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Stage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StageValidator {
	boolean validate();

	boolean validateStage(String value);

	boolean validateDisplayName(String value);

	boolean validateCondition(String value);

	boolean validateLockBehavior(LOCK_BEHAVIOR value);

	boolean validateTrigger(STAGE_TRIGGER value);

	boolean validateIsSkippable(Boolean value);

	boolean validateDependsOn(EList<String> value);

	boolean validatePool(Pool value);

	boolean validateVariables(EList<VariableDefinition> value);

	boolean validateJobs(EList<JobElement> value);

	boolean validateTemplateContext(TemplateContext value);
}
