/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.SettableVariables;
import com.mddoai.metamodel.azuredevops.azuredevopsMM.TARGET_COMMANDS;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.StepTarget}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StepTargetValidator {
	boolean validate();

	boolean validateContainer(String value);

	boolean validateCommands(TARGET_COMMANDS value);

	boolean validateSettableVariables(SettableVariables value);
}
