/**
 *
 * $Id$
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.validation;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.StepTarget;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Step}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StepValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDisplayName(String value);

	boolean validateCondition(String value);

	boolean validateContinueOnError(Boolean value);

	boolean validateEnabled(Boolean value);

	boolean validateTimeoutInMinutes(String value);

	boolean validateRetryCountOnTaskFailure(String value);

	boolean validateEnv(EMap<String, String> value);

	boolean validateTarget(StepTarget value);
}
