stages:
  - build
  - unitTest
  - lintCheck

default:
  image:
    name: gradle:jdk21



build:
  stage: build
  script:
    - gradle clean build -x test


unitTest:
  stage: unitTest
  script:
    - gradle test


lintCheck:
  stage: lintCheck
  script:
    - gradle check


