#

pluginName = com.mddoai.metamodel.gitlab Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Pipeline_type = Pipeline
_UI_Job_type = Job
_UI_Artifact_type = Artifact
_UI_Report_type = Report
_UI_Comand_type = Comand
_UI_BeforeScript_type = Before Script
_UI_Script_type = Script
_UI_Tags_type = Tags
_UI_Tag_type = Tag
_UI_Only_type = Only
_UI_OnlyBranches_type = Only Branches
_UI_Dependencies_type = Dependencies
_UI_Dependency_type = Dependency
_UI_Variables_type = Variables
_UI_Variable_type = Variable
_UI_Path_type = Path
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Pipeline_stages_feature = Stages
_UI_Pipeline_jobs_feature = Jobs
_UI_Pipeline_variables_feature = Variables
_UI_Job_name_feature = Name
_UI_Job_stage_feature = Stage
_UI_Job_artifacts_feature = Artifacts
_UI_Job_script_feature = Script
_UI_Job_beforeScript_feature = Before Script
_UI_Job_image_feature = Image
_UI_Job_tags_feature = Tags
_UI_Job_only_feature = Only
_UI_Job_dependencies_feature = Dependencies
_UI_Job_when_feature = When
_UI_Artifact_when_feature = When
_UI_Artifact_reports_feature = Reports
_UI_Artifact_paths_feature = Paths
_UI_Report_junit_feature = Junit
_UI_Comand_comand_feature = Comand
_UI_BeforeScript_commands_feature = Commands
_UI_Script_commands_feature = Commands
_UI_Tags_tags_feature = Tags
_UI_Tag_tag_feature = Tag
_UI_Only_branches_feature = Branches
_UI_OnlyBranches_branch_feature = Branch
_UI_Dependencies_dependencies_feature = Dependencies
_UI_Dependency_dependency_feature = Dependency
_UI_Variables_variables_feature = Variables
_UI_Variable_name_feature = Name
_UI_Variable_value_feature = Value
_UI_Path_path_feature = Path
_UI_Unknown_feature = Unspecified

_UI_Rule_type = Rule
_UI_Workflow_type = Workflow
_UI_Pipeline_workflow_feature = Workflow
_UI_Rule_if_feature = If
_UI_Rule_when_feature = When
_UI_Rule_changes_feature = Changes
_UI_Rule_exists_feature = Exists
_UI_Rule_variables_feature = Variables
_UI_Workflow_rules_feature = Rules
_UI_Matrix_type = Matrix
_UI_Matrix_abc_feature = Abc
_UI_Rule__type = Rule 
_UI_Image_type = Image
_UI_Docker_type = Docker
_UI_Kubernetes_type = Kubernetes
_UI_Service_type = Service
_UI_Cache_type = Cache
_UI_Key_type = Key
_UI_Need_type = Need
_UI_Environment_type = Environment
_UI_AfterScript_type = After Script
_UI_Default_type = Default
_UI_Retry_type = Retry
_UI_Axis_type = Axis
_UI_Parallel_type = Parallel
_UI_Pipeline_default_feature = Default
_UI_Job_allowFailure_feature = Allow Failure
_UI_Job_timeout_feature = Timeout
_UI_Job_interruptible_feature = Interruptible
_UI_Job_resourceGroup_feature = Resource Group
_UI_Job_afterScript_feature = After Script
_UI_Job_cache_feature = Cache
_UI_Job_rules_feature = Rules
_UI_Job_needs_feature = Needs
_UI_Job_services_feature = Services
_UI_Job_environment_feature = Environment
_UI_Job_retry_feature = Retry
_UI_Job_variables_feature = Variables
_UI_Job_parallel_feature = Parallel
_UI_Artifact_name_feature = Name
_UI_Artifact_expireIn_feature = Expire In
_UI_Artifact_expose_as_feature = Expose as
_UI_Artifact_untracked_feature = Untracked
_UI_Artifact_exclude_feature = Exclude
_UI_Report_coverage_report_feature = Coverage report
_UI_Report_dotenv_feature = Dotenv
_UI_Report_cobertura_feature = Cobertura
_UI_Variable_description_feature = Description
_UI_Variable_expand_feature = Expand
_UI_Rule__if__feature = If 
_UI_Rule__when_feature = When
_UI_Rule__changes_feature = Changes
_UI_Rule__exists_feature = Exists
_UI_Rule__allowFailure_feature = Allow Failure
_UI_Rule__variables_feature = Variables
_UI_Image_name_feature = Name
_UI_Image_entrypoint_feature = Entrypoint
_UI_Image_docker_feature = Docker
_UI_Image_kubernetes_feature = Kubernetes
_UI_Image_pull_policy_feature = Pull policy
_UI_Docker_platform_feature = Platform
_UI_Docker_user_feature = User
_UI_Kubernetes_user_feature = User
_UI_Service_name_feature = Name
_UI_Service_alias_feature = Alias
_UI_Service_entrypoint_feature = Entrypoint
_UI_Service_commands_feature = Commands
_UI_Service_docker_feature = Docker
_UI_Service_kubernetes_feature = Kubernetes
_UI_Service_pull_policy_feature = Pull policy
_UI_Cache_key_feature = Key
_UI_Cache_paths_feature = Paths
_UI_Cache_untracked_feature = Untracked
_UI_Cache_unprotect_feature = Unprotect
_UI_Cache_when_feature = When
_UI_Key_name_feature = Name
_UI_Key_files_feature = Files
_UI_Key_files_commits_feature = Files commits
_UI_Key_prefix_feature = Prefix
_UI_Need_job_feature = Job
_UI_Need_artifacts_feature = Artifacts
_UI_Need_project_feature = Project
_UI_Need_ref_feature = Ref
_UI_Need_pipeline_feature = Pipeline
_UI_Need_optional_feature = Optional
_UI_Environment_name_feature = Name
_UI_Environment_url_feature = Url
_UI_Environment_on_stop_feature = On stop
_UI_Environment_action_feature = Action
_UI_Environment_auto_stop_in_feature = Auto stop in
_UI_Environment_kubernetes_feature = Kubernetes
_UI_AfterScript_commands_feature = Commands
_UI_Default_image_feature = Image
_UI_Default_services_feature = Services
_UI_Default_tags_feature = Tags
_UI_Default_cache_feature = Cache
_UI_Default_beforeScript_feature = Before Script
_UI_Default_afterScript_feature = After Script
_UI_Default_timeout_feature = Timeout
_UI_Default_interruptible_feature = Interruptible
_UI_Default_retry_feature = Retry
_UI_Retry_max_feature = Max
_UI_Retry_when_feature = When
_UI_Axis_name_feature = Name
_UI_Axis_values_feature = Values
_UI_Matrix_axes_feature = Axes
_UI_Parallel_count_feature = Count
_UI_Parallel_matrix_feature = Matrix
