/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.Expression;
import com.mddoai.metamodel.github.githubMM.VariableDeclaration;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.Container}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerValidator {
	boolean validate();

	boolean validateImage(Expression value);

	boolean validateUsername(Expression value);

	boolean validatePassword(Expression value);

	boolean validateEnvironmentVariables(EMap<VariableDeclaration, Expression> value);

	boolean validatePorts(EList<Expression> value);

	boolean validateVolumes(EList<Expression> value);

	boolean validateOptions(Expression value);
}
