/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.Agent;
import com.mddoai.metamodel.github.githubMM.ConcurrencyGroup;
import com.mddoai.metamodel.github.githubMM.Container;
import com.mddoai.metamodel.github.githubMM.Defaults;
import com.mddoai.metamodel.github.githubMM.Expression;
import com.mddoai.metamodel.github.githubMM.Job;
import com.mddoai.metamodel.github.githubMM.Matrix;
import com.mddoai.metamodel.github.githubMM.Output;
import com.mddoai.metamodel.github.githubMM.PERMISSIONS;
import com.mddoai.metamodel.github.githubMM.PERMISSION_SCOPES;
import com.mddoai.metamodel.github.githubMM.StagingEnvironment;
import com.mddoai.metamodel.github.githubMM.VariableDeclaration;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.Job}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JobValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateJobName(Expression value);

	boolean validatePermissions(EMap<PERMISSION_SCOPES, PERMISSIONS> value);

	boolean validateDependsOn(EList<Job> value);

	boolean validateNecessaryFor(EList<Job> value);

	boolean validateIfCondition(Expression value);

	boolean validateAgent(Agent value);

	boolean validateContainer(Container value);

	boolean validateStagingEnvironment(StagingEnvironment value);

	boolean validateDefaults(Defaults value);

	boolean validateEnvironmentVariables(EMap<VariableDeclaration, Expression> value);

	boolean validateServices(EMap<String, Container> value);

	boolean validateConcurrencyGroup(ConcurrencyGroup value);

	boolean validateTimeoutMinutes(Expression value);

	boolean validateContinueOnError(Expression value);

	boolean validateStrategy(Matrix value);

	boolean validateOutputs(EList<Output> value);
}
