/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.Expression;
import com.mddoai.metamodel.github.githubMM.MatrixAxis;
import com.mddoai.metamodel.github.githubMM.MatrixCombination;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.Matrix}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MatrixValidator {
	boolean validate();

	boolean validateAxes(EList<MatrixAxis> value);

	boolean validateIncludes(EList<MatrixCombination> value);

	boolean validateExcludes(EList<MatrixCombination> value);

	boolean validateFailFast(Expression value);

	boolean validateMaxParallel(Expression value);
}
