/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.Expression;
import com.mddoai.metamodel.github.githubMM.VariableDeclaration;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.Package}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageValidator {
	boolean validate();

	boolean validateUses(Expression value);

	boolean validateArgs(EMap<VariableDeclaration, Expression> value);

	boolean validateEntrypoint(Expression value);

	boolean validateContainerArgs(Expression value);
}
