/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.Expression;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.SpecifiedPathsTrigger}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpecifiedPathsTriggerValidator {
	boolean validate();

	boolean validatePaths(EList<Expression> value);

	boolean validateIgnoreSpecifiedPaths(boolean value);
}
