/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.Expression;
import com.mddoai.metamodel.github.githubMM.VariableDeclaration;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.Step}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StepValidator {
	boolean validate();

	boolean validateId(String value);

	boolean validateName(Expression value);

	boolean validateTimeoutMinutes(Expression value);

	boolean validateContinueOnError(Expression value);

	boolean validateShell(Expression value);

	boolean validateWorkingDirectory(Expression value);

	boolean validateEnvironmentVariables(EMap<VariableDeclaration, Expression> value);
}
