/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.Output;
import com.mddoai.metamodel.github.githubMM.Secret;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.WorkflowCallTrigger}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowCallTriggerValidator {
	boolean validate();

	boolean validateOutputs(EList<Output> value);

	boolean validateSecrets(EList<Secret> value);
}
