/**
 *
 * $Id$
 */
package com.mddoai.metamodel.github.githubMM.validation;

import com.mddoai.metamodel.github.githubMM.ConcurrencyGroup;
import com.mddoai.metamodel.github.githubMM.Defaults;
import com.mddoai.metamodel.github.githubMM.Expression;
import com.mddoai.metamodel.github.githubMM.Job;
import com.mddoai.metamodel.github.githubMM.PERMISSIONS;
import com.mddoai.metamodel.github.githubMM.PERMISSION_SCOPES;
import com.mddoai.metamodel.github.githubMM.Trigger;
import com.mddoai.metamodel.github.githubMM.VariableDeclaration;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.github.githubMM.Workflow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowValidator {
	boolean validate();

	boolean validateName(Expression value);

	boolean validateRunName(Expression value);

	boolean validateTriggers(EList<Trigger> value);

	boolean validatePermissions(EMap<PERMISSION_SCOPES, PERMISSIONS> value);

	boolean validateDefaults(Defaults value);

	boolean validateEnvironmentVariables(EMap<VariableDeclaration, Expression> value);

	boolean validateConcurrencyGroup(ConcurrencyGroup value);

	boolean validateJobs(EList<Job> value);
}
