/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Path;
import com.mddoai.metamodel.gitlab.gitlabMM.Report;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Artifact}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArtifactValidator {
	boolean validate();

	boolean validateWhen(String value);

	boolean validateReports(Report value);

	boolean validatePaths(EList<Path> value);

	boolean validateName(String value);

	boolean validateExpireIn(String value);

	boolean validateExposeAs(String value);

	boolean validateUntracked(boolean value);

	boolean validateExclude(EList<String> value);
}
