/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.ArtifactReports;
import com.mddoai.metamodel.gitlab.gitlabMM.ArtifactsWhenType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Artifacts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArtifactsValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validatePaths(EList<String> value);

	boolean validateWhen(ArtifactsWhenType value);

	boolean validateExpireIn(String value);

	boolean validateExposeAs(String value);

	boolean validateUntracked(Boolean value);

	boolean validateExclude(EList<String> value);

	boolean validateReports(ArtifactReports value);
}
