/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Key;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Cache}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CacheValidator {
	boolean validate();

	boolean validateKey(Key value);

	boolean validatePaths(EList<String> value);

	boolean validateUntracked(boolean value);

	boolean validateUnprotect(boolean value);

	boolean validateWhen(String value);
}
