/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Cache;
import com.mddoai.metamodel.gitlab.gitlabMM.Image;
import com.mddoai.metamodel.gitlab.gitlabMM.Retry;
import com.mddoai.metamodel.gitlab.gitlabMM.Service;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Default}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DefaultValidator {
	boolean validate();

	boolean validateImage(Image value);

	boolean validateBeforeScript(EList<String> value);

	boolean validateAfterScript(EList<String> value);

	boolean validateServices(EList<Service> value);

	boolean validateCache(Cache value);

	boolean validateTags(EList<String> value);

	boolean validateTimeout(String value);

	boolean validateInterruptible(Boolean value);

	boolean validateRetry(Retry value);
}
