/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Kubernetes;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Environment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnvironmentValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateUrl(String value);

	boolean validateOnStop(String value);

	boolean validateAction(String value);

	boolean validateAutoStopIn(String value);

	boolean validateKubernetes(Kubernetes value);
}
