/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.DockerOptions;
import com.mddoai.metamodel.gitlab.gitlabMM.KubernetesOptions;
import com.mddoai.metamodel.gitlab.gitlabMM.PullPolicy;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Image}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImageValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateEntrypoint(EList<String> value);

	boolean validatePullPolicy(PullPolicy value);

	boolean validateDocker(DockerOptions value);

	boolean validateKubernetes(KubernetesOptions value);
}
