/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.AfterScript;
import com.mddoai.metamodel.gitlab.gitlabMM.Artifact;
import com.mddoai.metamodel.gitlab.gitlabMM.BeforeScript;
import com.mddoai.metamodel.gitlab.gitlabMM.Cache;
import com.mddoai.metamodel.gitlab.gitlabMM.Dependencies;
import com.mddoai.metamodel.gitlab.gitlabMM.Environment;
import com.mddoai.metamodel.gitlab.gitlabMM.GitlabRule;
import com.mddoai.metamodel.gitlab.gitlabMM.Image;
import com.mddoai.metamodel.gitlab.gitlabMM.Need;
import com.mddoai.metamodel.gitlab.gitlabMM.Only;
import com.mddoai.metamodel.gitlab.gitlabMM.Parallel;
import com.mddoai.metamodel.gitlab.gitlabMM.Retry;
import com.mddoai.metamodel.gitlab.gitlabMM.Script;
import com.mddoai.metamodel.gitlab.gitlabMM.Service;
import com.mddoai.metamodel.gitlab.gitlabMM.Tags;
import com.mddoai.metamodel.gitlab.gitlabMM.Variables;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Job}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JobValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateStage(String value);

	boolean validateArtifacts(Artifact value);

	boolean validateScript(Script value);

	boolean validateBeforeScript(BeforeScript value);

	boolean validateTags(Tags value);

	boolean validateOnly(Only value);

	boolean validateDependencies(Dependencies value);

	boolean validateWhen(String value);

	boolean validateImage(Image value);

	boolean validateAllowFailure(boolean value);

	boolean validateTimeout(String value);

	boolean validateInterruptible(boolean value);

	boolean validateResourceGroup(String value);

	boolean validateAfterScript(AfterScript value);

	boolean validateCache(Cache value);

	boolean validateRules(EList<GitlabRule> value);

	boolean validateNeeds(EList<Need> value);

	boolean validateServices(EList<Service> value);

	boolean validateEnvironment(Environment value);

	boolean validateRetry(Retry value);

	boolean validateVariables(Variables value);

	boolean validateParallel(Parallel value);
}
