/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Artifacts;
import com.mddoai.metamodel.gitlab.gitlabMM.Cache;
import com.mddoai.metamodel.gitlab.gitlabMM.Environment;
import com.mddoai.metamodel.gitlab.gitlabMM.Image;
import com.mddoai.metamodel.gitlab.gitlabMM.Need;
import com.mddoai.metamodel.gitlab.gitlabMM.Parallel;
import com.mddoai.metamodel.gitlab.gitlabMM.Retry;
import com.mddoai.metamodel.gitlab.gitlabMM.Rule;
import com.mddoai.metamodel.gitlab.gitlabMM.Service;
import com.mddoai.metamodel.gitlab.gitlabMM.Variable;
import com.mddoai.metamodel.gitlab.gitlabMM.WhenType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Job}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JobValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateStage(String value);

	boolean validateImage(Image value);

	boolean validateScript(EList<String> value);

	boolean validateBeforeScript(EList<String> value);

	boolean validateAfterScript(EList<String> value);

	boolean validateServices(EList<Service> value);

	boolean validateVariables(EList<Variable> value);

	boolean validateArtifacts(Artifacts value);

	boolean validateCache(Cache value);

	boolean validateNeeds(EList<Need> value);

	boolean validateRules(EList<Rule> value);

	boolean validateTags(EList<String> value);

	boolean validateOnly(EList<String> value);

	boolean validateExcept(EList<String> value);

	boolean validateWhen(WhenType value);

	boolean validateAllowFailure(Boolean value);

	boolean validateTimeout(String value);

	boolean validateInterruptible(Boolean value);

	boolean validateResourceGroup(String value);

	boolean validateRetry(Retry value);

	boolean validateParallel(Parallel value);

	boolean validateEnvironment(Environment value);

	boolean validateDependencies(EList<String> value);
}
