/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Need}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NeedValidator {
	boolean validate();

	boolean validateJob(String value);

	boolean validateArtifacts(Boolean value);

	boolean validateOptional(Boolean value);

	boolean validateProject(String value);

	boolean validateRef(String value);

	boolean validatePipeline(String value);
}
