/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Matrix;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Parallel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParallelValidator {
	boolean validate();

	boolean validateCount(Integer value);

	boolean validateMatrix(Matrix value);
}
