/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Report}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReportValidator {
	boolean validate();

	boolean validateJunit(String value);

	boolean validateCoverage_report(String value);

	boolean validateDotenv(String value);

	boolean validateCobertura(String value);
}
