/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Variables;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Rule_}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Rule_Validator {
	boolean validate();

	boolean validateIf_(String value);

	boolean validateWhen(String value);

	boolean validateChanges(EList<String> value);

	boolean validateExists(EList<String> value);

	boolean validateAllowFailure(boolean value);

	boolean validateVariables(Variables value);
}
