/**
 *
 * $Id$
 */
package com.mddoai.metamodel.gitlab.gitlabMM.validation;

import com.mddoai.metamodel.gitlab.gitlabMM.Command;
import com.mddoai.metamodel.gitlab.gitlabMM.Docker;
import com.mddoai.metamodel.gitlab.gitlabMM.Kubernetes;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.gitlab.gitlabMM.Service}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateAlias(String value);

	boolean validateEntrypoint(EList<String> value);

	boolean validateCommands(EList<Command> value);

	boolean validateDocker(Docker value);

	boolean validateKubernetes(Kubernetes value);

	boolean validatePullPolicy(EList<String> value);
}
