/**
 */
package com.mddoai.metamodel.azuredevops.azuredevopsMM.provider;

import com.mddoai.metamodel.azuredevops.azuredevopsMM.util.AzuredevopsMMAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AzuredevopsMMItemProviderAdapterFactory extends AzuredevopsMMAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AzuredevopsMMItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Pipeline} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PipelineItemProvider pipelineItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Pipeline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPipelineAdapter() {
		if (pipelineItemProvider == null) {
			pipelineItemProvider = new PipelineItemProvider(this);
		}

		return pipelineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Extends} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtendsItemProvider extendsItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Extends}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtendsAdapter() {
		if (extendsItemProvider == null) {
			extendsItemProvider = new ExtendsItemProvider(this);
		}

		return extendsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Stage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StageItemProvider stageItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Stage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStageAdapter() {
		if (stageItemProvider == null) {
			stageItemProvider = new StageItemProvider(this);
		}

		return stageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.StageTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StageTemplateItemProvider stageTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.StageTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStageTemplateAdapter() {
		if (stageTemplateItemProvider == null) {
			stageTemplateItemProvider = new StageTemplateItemProvider(this);
		}

		return stageTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Job} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JobItemProvider jobItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Job}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJobAdapter() {
		if (jobItemProvider == null) {
			jobItemProvider = new JobItemProvider(this);
		}

		return jobItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeploymentJob} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentJobItemProvider deploymentJobItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeploymentJob}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentJobAdapter() {
		if (deploymentJobItemProvider == null) {
			deploymentJobItemProvider = new DeploymentJobItemProvider(this);
		}

		return deploymentJobItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.JobTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JobTemplateItemProvider jobTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.JobTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJobTemplateAdapter() {
		if (jobTemplateItemProvider == null) {
			jobTemplateItemProvider = new JobTemplateItemProvider(this);
		}

		return jobTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Environment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentItemProvider environmentItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Environment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvironmentAdapter() {
		if (environmentItemProvider == null) {
			environmentItemProvider = new EnvironmentItemProvider(this);
		}

		return environmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeploymentStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentStrategyItemProvider deploymentStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeploymentStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentStrategyAdapter() {
		if (deploymentStrategyItemProvider == null) {
			deploymentStrategyItemProvider = new DeploymentStrategyItemProvider(this);
		}

		return deploymentStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.RunOnceStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RunOnceStrategyItemProvider runOnceStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.RunOnceStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRunOnceStrategyAdapter() {
		if (runOnceStrategyItemProvider == null) {
			runOnceStrategyItemProvider = new RunOnceStrategyItemProvider(this);
		}

		return runOnceStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.RollingStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RollingStrategyItemProvider rollingStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.RollingStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRollingStrategyAdapter() {
		if (rollingStrategyItemProvider == null) {
			rollingStrategyItemProvider = new RollingStrategyItemProvider(this);
		}

		return rollingStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CanaryStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CanaryStrategyItemProvider canaryStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CanaryStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCanaryStrategyAdapter() {
		if (canaryStrategyItemProvider == null) {
			canaryStrategyItemProvider = new CanaryStrategyItemProvider(this);
		}

		return canaryStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeployHook} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeployHookItemProvider deployHookItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DeployHook}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeployHookAdapter() {
		if (deployHookItemProvider == null) {
			deployHookItemProvider = new DeployHookItemProvider(this);
		}

		return deployHookItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.OnSuccessOrFailureHook} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OnSuccessOrFailureHookItemProvider onSuccessOrFailureHookItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.OnSuccessOrFailureHook}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOnSuccessOrFailureHookAdapter() {
		if (onSuccessOrFailureHookItemProvider == null) {
			onSuccessOrFailureHookItemProvider = new OnSuccessOrFailureHookItemProvider(this);
		}

		return onSuccessOrFailureHookItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.JobStrategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JobStrategyItemProvider jobStrategyItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.JobStrategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJobStrategyAdapter() {
		if (jobStrategyItemProvider == null) {
			jobStrategyItemProvider = new JobStrategyItemProvider(this);
		}

		return jobStrategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatrixEntryItemProvider matrixEntryItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatrixEntryAdapter() {
		if (matrixEntryItemProvider == null) {
			matrixEntryItemProvider = new MatrixEntryItemProvider(this);
		}

		return matrixEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatrixVariableItemProvider matrixVariableItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatrixVariableAdapter() {
		if (matrixVariableItemProvider == null) {
			matrixVariableItemProvider = new MatrixVariableItemProvider(this);
		}

		return matrixVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.JobUses} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JobUsesItemProvider jobUsesItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.JobUses}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJobUsesAdapter() {
		if (jobUsesItemProvider == null) {
			jobUsesItemProvider = new JobUsesItemProvider(this);
		}

		return jobUsesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Pool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PoolItemProvider poolItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Pool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPoolAdapter() {
		if (poolItemProvider == null) {
			poolItemProvider = new PoolItemProvider(this);
		}

		return poolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Workspace} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkspaceItemProvider workspaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Workspace}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkspaceAdapter() {
		if (workspaceItemProvider == null) {
			workspaceItemProvider = new WorkspaceItemProvider(this);
		}

		return workspaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerAlias} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerAliasItemProvider containerAliasItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerAlias}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerAliasAdapter() {
		if (containerAliasItemProvider == null) {
			containerAliasItemProvider = new ContainerAliasItemProvider(this);
		}

		return containerAliasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerImage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerImageItemProvider containerImageItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerImage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerImageAdapter() {
		if (containerImageItemProvider == null) {
			containerImageItemProvider = new ContainerImageItemProvider(this);
		}

		return containerImageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.MountReadOnly} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MountReadOnlyItemProvider mountReadOnlyItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.MountReadOnly}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMountReadOnlyAdapter() {
		if (mountReadOnlyItemProvider == null) {
			mountReadOnlyItemProvider = new MountReadOnlyItemProvider(this);
		}

		return mountReadOnlyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceEntryItemProvider serviceEntryItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceEntryAdapter() {
		if (serviceEntryItemProvider == null) {
			serviceEntryItemProvider = new ServiceEntryItemProvider(this);
		}

		return serviceEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.TaskStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TaskStepItemProvider taskStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.TaskStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTaskStepAdapter() {
		if (taskStepItemProvider == null) {
			taskStepItemProvider = new TaskStepItemProvider(this);
		}

		return taskStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ScriptStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScriptStepItemProvider scriptStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ScriptStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScriptStepAdapter() {
		if (scriptStepItemProvider == null) {
			scriptStepItemProvider = new ScriptStepItemProvider(this);
		}

		return scriptStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.BashStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BashStepItemProvider bashStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.BashStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBashStepAdapter() {
		if (bashStepItemProvider == null) {
			bashStepItemProvider = new BashStepItemProvider(this);
		}

		return bashStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PowershellStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PowershellStepItemProvider powershellStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PowershellStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPowershellStepAdapter() {
		if (powershellStepItemProvider == null) {
			powershellStepItemProvider = new PowershellStepItemProvider(this);
		}

		return powershellStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PwshStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PwshStepItemProvider pwshStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PwshStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPwshStepAdapter() {
		if (pwshStepItemProvider == null) {
			pwshStepItemProvider = new PwshStepItemProvider(this);
		}

		return pwshStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CheckoutStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CheckoutStepItemProvider checkoutStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CheckoutStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCheckoutStepAdapter() {
		if (checkoutStepItemProvider == null) {
			checkoutStepItemProvider = new CheckoutStepItemProvider(this);
		}

		return checkoutStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DownloadStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DownloadStepItemProvider downloadStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DownloadStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDownloadStepAdapter() {
		if (downloadStepItemProvider == null) {
			downloadStepItemProvider = new DownloadStepItemProvider(this);
		}

		return downloadStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DownloadBuildStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DownloadBuildStepItemProvider downloadBuildStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.DownloadBuildStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDownloadBuildStepAdapter() {
		if (downloadBuildStepItemProvider == null) {
			downloadBuildStepItemProvider = new DownloadBuildStepItemProvider(this);
		}

		return downloadBuildStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.GetPackageStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetPackageStepItemProvider getPackageStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.GetPackageStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetPackageStepAdapter() {
		if (getPackageStepItemProvider == null) {
			getPackageStepItemProvider = new GetPackageStepItemProvider(this);
		}

		return getPackageStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PublishStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PublishStepItemProvider publishStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PublishStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPublishStepAdapter() {
		if (publishStepItemProvider == null) {
			publishStepItemProvider = new PublishStepItemProvider(this);
		}

		return publishStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ReviewAppStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReviewAppStepItemProvider reviewAppStepItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ReviewAppStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReviewAppStepAdapter() {
		if (reviewAppStepItemProvider == null) {
			reviewAppStepItemProvider = new ReviewAppStepItemProvider(this);
		}

		return reviewAppStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.StepTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepTemplateItemProvider stepTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.StepTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepTemplateAdapter() {
		if (stepTemplateItemProvider == null) {
			stepTemplateItemProvider = new StepTemplateItemProvider(this);
		}

		return stepTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.StepTarget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepTargetItemProvider stepTargetItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.StepTarget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepTargetAdapter() {
		if (stepTargetItemProvider == null) {
			stepTargetItemProvider = new StepTargetItemProvider(this);
		}

		return stepTargetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.SettableVariables} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SettableVariablesItemProvider settableVariablesItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.SettableVariables}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSettableVariablesAdapter() {
		if (settableVariablesItemProvider == null) {
			settableVariablesItemProvider = new SettableVariablesItemProvider(this);
		}

		return settableVariablesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Trigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriggerItemProvider triggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Trigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriggerAdapter() {
		if (triggerItemProvider == null) {
			triggerItemProvider = new TriggerItemProvider(this);
		}

		return triggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PrTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrTriggerItemProvider prTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PrTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrTriggerAdapter() {
		if (prTriggerItemProvider == null) {
			prTriggerItemProvider = new PrTriggerItemProvider(this);
		}

		return prTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CronSchedule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CronScheduleItemProvider cronScheduleItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.CronSchedule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCronScheduleAdapter() {
		if (cronScheduleItemProvider == null) {
			cronScheduleItemProvider = new CronScheduleItemProvider(this);
		}

		return cronScheduleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.IncludeExcludeFilters} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IncludeExcludeFiltersItemProvider includeExcludeFiltersItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.IncludeExcludeFilters}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIncludeExcludeFiltersAdapter() {
		if (includeExcludeFiltersItemProvider == null) {
			includeExcludeFiltersItemProvider = new IncludeExcludeFiltersItemProvider(this);
		}

		return includeExcludeFiltersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TemplateParameterAssignmentItemProvider templateParameterAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTemplateParameterAssignmentAdapter() {
		if (templateParameterAssignmentItemProvider == null) {
			templateParameterAssignmentItemProvider = new TemplateParameterAssignmentItemProvider(this);
		}

		return templateParameterAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableNameItemProvider variableNameItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableNameAdapter() {
		if (variableNameItemProvider == null) {
			variableNameItemProvider = new VariableNameItemProvider(this);
		}

		return variableNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableGroupItemProvider variableGroupItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableGroupAdapter() {
		if (variableGroupItemProvider == null) {
			variableGroupItemProvider = new VariableGroupItemProvider(this);
		}

		return variableGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableTemplateItemProvider variableTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.VariableTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableTemplateAdapter() {
		if (variableTemplateItemProvider == null) {
			variableTemplateItemProvider = new VariableTemplateItemProvider(this);
		}

		return variableTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Resources} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourcesItemProvider resourcesItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.Resources}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResourcesAdapter() {
		if (resourcesItemProvider == null) {
			resourcesItemProvider = new ResourcesItemProvider(this);
		}

		return resourcesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.BuildResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuildResourceItemProvider buildResourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.BuildResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBuildResourceAdapter() {
		if (buildResourceItemProvider == null) {
			buildResourceItemProvider = new BuildResourceItemProvider(this);
		}

		return buildResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerResourceItemProvider containerResourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerResourceAdapter() {
		if (containerResourceItemProvider == null) {
			containerResourceItemProvider = new ContainerResourceItemProvider(this);
		}

		return containerResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerResourceTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerResourceTriggerItemProvider containerResourceTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.ContainerResourceTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerResourceTriggerAdapter() {
		if (containerResourceTriggerItemProvider == null) {
			containerResourceTriggerItemProvider = new ContainerResourceTriggerItemProvider(this);
		}

		return containerResourceTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PipelineResourceItemProvider pipelineResourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPipelineResourceAdapter() {
		if (pipelineResourceItemProvider == null) {
			pipelineResourceItemProvider = new PipelineResourceItemProvider(this);
		}

		return pipelineResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResourceTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PipelineResourceTriggerItemProvider pipelineResourceTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PipelineResourceTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPipelineResourceTriggerAdapter() {
		if (pipelineResourceTriggerItemProvider == null) {
			pipelineResourceTriggerItemProvider = new PipelineResourceTriggerItemProvider(this);
		}

		return pipelineResourceTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.RepositoryResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoryResourceItemProvider repositoryResourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.RepositoryResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepositoryResourceAdapter() {
		if (repositoryResourceItemProvider == null) {
			repositoryResourceItemProvider = new RepositoryResourceItemProvider(this);
		}

		return repositoryResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.WebhookResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WebhookResourceItemProvider webhookResourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.WebhookResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWebhookResourceAdapter() {
		if (webhookResourceItemProvider == null) {
			webhookResourceItemProvider = new WebhookResourceItemProvider(this);
		}

		return webhookResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.WebhookFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WebhookFilterItemProvider webhookFilterItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.WebhookFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWebhookFilterAdapter() {
		if (webhookFilterItemProvider == null) {
			webhookFilterItemProvider = new WebhookFilterItemProvider(this);
		}

		return webhookFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PackageResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PackageResourceItemProvider packageResourceItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.PackageResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPackageResourceAdapter() {
		if (packageResourceItemProvider == null) {
			packageResourceItemProvider = new PackageResourceItemProvider(this);
		}

		return packageResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvEntryItemProvider envEntryItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvEntryAdapter() {
		if (envEntryItemProvider == null) {
			envEntryItemProvider = new EnvEntryItemProvider(this);
		}

		return envEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputEntryItemProvider inputEntryItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputEntryAdapter() {
		if (inputEntryItemProvider == null) {
			inputEntryItemProvider = new InputEntryItemProvider(this);
		}

		return inputEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.TemplateContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TemplateContextItemProvider templateContextItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.azuredevops.azuredevopsMM.TemplateContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTemplateContextAdapter() {
		if (templateContextItemProvider == null) {
			templateContextItemProvider = new TemplateContextItemProvider(this);
		}

		return templateContextItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (pipelineItemProvider != null)
			pipelineItemProvider.dispose();
		if (extendsItemProvider != null)
			extendsItemProvider.dispose();
		if (stageItemProvider != null)
			stageItemProvider.dispose();
		if (stageTemplateItemProvider != null)
			stageTemplateItemProvider.dispose();
		if (jobItemProvider != null)
			jobItemProvider.dispose();
		if (deploymentJobItemProvider != null)
			deploymentJobItemProvider.dispose();
		if (jobTemplateItemProvider != null)
			jobTemplateItemProvider.dispose();
		if (environmentItemProvider != null)
			environmentItemProvider.dispose();
		if (deploymentStrategyItemProvider != null)
			deploymentStrategyItemProvider.dispose();
		if (runOnceStrategyItemProvider != null)
			runOnceStrategyItemProvider.dispose();
		if (rollingStrategyItemProvider != null)
			rollingStrategyItemProvider.dispose();
		if (canaryStrategyItemProvider != null)
			canaryStrategyItemProvider.dispose();
		if (deployHookItemProvider != null)
			deployHookItemProvider.dispose();
		if (onSuccessOrFailureHookItemProvider != null)
			onSuccessOrFailureHookItemProvider.dispose();
		if (jobStrategyItemProvider != null)
			jobStrategyItemProvider.dispose();
		if (matrixEntryItemProvider != null)
			matrixEntryItemProvider.dispose();
		if (matrixVariableItemProvider != null)
			matrixVariableItemProvider.dispose();
		if (jobUsesItemProvider != null)
			jobUsesItemProvider.dispose();
		if (poolItemProvider != null)
			poolItemProvider.dispose();
		if (workspaceItemProvider != null)
			workspaceItemProvider.dispose();
		if (containerAliasItemProvider != null)
			containerAliasItemProvider.dispose();
		if (containerImageItemProvider != null)
			containerImageItemProvider.dispose();
		if (mountReadOnlyItemProvider != null)
			mountReadOnlyItemProvider.dispose();
		if (serviceEntryItemProvider != null)
			serviceEntryItemProvider.dispose();
		if (taskStepItemProvider != null)
			taskStepItemProvider.dispose();
		if (scriptStepItemProvider != null)
			scriptStepItemProvider.dispose();
		if (bashStepItemProvider != null)
			bashStepItemProvider.dispose();
		if (powershellStepItemProvider != null)
			powershellStepItemProvider.dispose();
		if (pwshStepItemProvider != null)
			pwshStepItemProvider.dispose();
		if (checkoutStepItemProvider != null)
			checkoutStepItemProvider.dispose();
		if (downloadStepItemProvider != null)
			downloadStepItemProvider.dispose();
		if (downloadBuildStepItemProvider != null)
			downloadBuildStepItemProvider.dispose();
		if (getPackageStepItemProvider != null)
			getPackageStepItemProvider.dispose();
		if (publishStepItemProvider != null)
			publishStepItemProvider.dispose();
		if (reviewAppStepItemProvider != null)
			reviewAppStepItemProvider.dispose();
		if (stepTemplateItemProvider != null)
			stepTemplateItemProvider.dispose();
		if (stepTargetItemProvider != null)
			stepTargetItemProvider.dispose();
		if (settableVariablesItemProvider != null)
			settableVariablesItemProvider.dispose();
		if (triggerItemProvider != null)
			triggerItemProvider.dispose();
		if (prTriggerItemProvider != null)
			prTriggerItemProvider.dispose();
		if (cronScheduleItemProvider != null)
			cronScheduleItemProvider.dispose();
		if (includeExcludeFiltersItemProvider != null)
			includeExcludeFiltersItemProvider.dispose();
		if (parameterItemProvider != null)
			parameterItemProvider.dispose();
		if (templateParameterAssignmentItemProvider != null)
			templateParameterAssignmentItemProvider.dispose();
		if (variableNameItemProvider != null)
			variableNameItemProvider.dispose();
		if (variableGroupItemProvider != null)
			variableGroupItemProvider.dispose();
		if (variableTemplateItemProvider != null)
			variableTemplateItemProvider.dispose();
		if (resourcesItemProvider != null)
			resourcesItemProvider.dispose();
		if (buildResourceItemProvider != null)
			buildResourceItemProvider.dispose();
		if (containerResourceItemProvider != null)
			containerResourceItemProvider.dispose();
		if (containerResourceTriggerItemProvider != null)
			containerResourceTriggerItemProvider.dispose();
		if (pipelineResourceItemProvider != null)
			pipelineResourceItemProvider.dispose();
		if (pipelineResourceTriggerItemProvider != null)
			pipelineResourceTriggerItemProvider.dispose();
		if (repositoryResourceItemProvider != null)
			repositoryResourceItemProvider.dispose();
		if (webhookResourceItemProvider != null)
			webhookResourceItemProvider.dispose();
		if (webhookFilterItemProvider != null)
			webhookFilterItemProvider.dispose();
		if (packageResourceItemProvider != null)
			packageResourceItemProvider.dispose();
		if (envEntryItemProvider != null)
			envEntryItemProvider.dispose();
		if (inputEntryItemProvider != null)
			inputEntryItemProvider.dispose();
		if (templateContextItemProvider != null)
			templateContextItemProvider.dispose();
	}

}
