/**
 */
package com.mddoai.metamodel.bambooMM.provider;

import com.mddoai.metamodel.bambooMM.util.BambooAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class BambooItemProviderAdapterFactory extends BambooAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BambooItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Plan} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlanItemProvider planItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Plan}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlanAdapter() {
		if (planItemProvider == null) {
			planItemProvider = new PlanItemProvider(this);
		}

		return planItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Stage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StageItemProvider stageItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Stage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStageAdapter() {
		if (stageItemProvider == null) {
			stageItemProvider = new StageItemProvider(this);
		}

		return stageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Job} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JobItemProvider jobItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Job}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJobAdapter() {
		if (jobItemProvider == null) {
			jobItemProvider = new JobItemProvider(this);
		}

		return jobItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.ScriptTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScriptTaskItemProvider scriptTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.ScriptTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScriptTaskAdapter() {
		if (scriptTaskItemProvider == null) {
			scriptTaskItemProvider = new ScriptTaskItemProvider(this);
		}

		return scriptTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.CleanTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CleanTaskItemProvider cleanTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.CleanTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCleanTaskAdapter() {
		if (cleanTaskItemProvider == null) {
			cleanTaskItemProvider = new CleanTaskItemProvider(this);
		}

		return cleanTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.CheckoutTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CheckoutTaskItemProvider checkoutTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.CheckoutTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCheckoutTaskAdapter() {
		if (checkoutTaskItemProvider == null) {
			checkoutTaskItemProvider = new CheckoutTaskItemProvider(this);
		}

		return checkoutTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.MavenTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MavenTaskItemProvider mavenTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.MavenTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMavenTaskAdapter() {
		if (mavenTaskItemProvider == null) {
			mavenTaskItemProvider = new MavenTaskItemProvider(this);
		}

		return mavenTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.InjectVariablesTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InjectVariablesTaskItemProvider injectVariablesTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.InjectVariablesTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInjectVariablesTaskAdapter() {
		if (injectVariablesTaskItemProvider == null) {
			injectVariablesTaskItemProvider = new InjectVariablesTaskItemProvider(this);
		}

		return injectVariablesTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.TestParserTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TestParserTaskItemProvider testParserTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.TestParserTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTestParserTaskAdapter() {
		if (testParserTaskItemProvider == null) {
			testParserTaskItemProvider = new TestParserTaskItemProvider(this);
		}

		return testParserTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.ArtifactDownloadTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArtifactDownloadTaskItemProvider artifactDownloadTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.ArtifactDownloadTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArtifactDownloadTaskAdapter() {
		if (artifactDownloadTaskItemProvider == null) {
			artifactDownloadTaskItemProvider = new ArtifactDownloadTaskItemProvider(this);
		}

		return artifactDownloadTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.ArtifactDownloadItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArtifactDownloadItemItemProvider artifactDownloadItemItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.ArtifactDownloadItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArtifactDownloadItemAdapter() {
		if (artifactDownloadItemItemProvider == null) {
			artifactDownloadItemItemProvider = new ArtifactDownloadItemItemProvider(this);
		}

		return artifactDownloadItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.AnyTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnyTaskItemProvider anyTaskItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.AnyTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnyTaskAdapter() {
		if (anyTaskItemProvider == null) {
			anyTaskItemProvider = new AnyTaskItemProvider(this);
		}

		return anyTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.TaskCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TaskConditionItemProvider taskConditionItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.TaskCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTaskConditionAdapter() {
		if (taskConditionItemProvider == null) {
			taskConditionItemProvider = new TaskConditionItemProvider(this);
		}

		return taskConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.PollingTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PollingTriggerItemProvider pollingTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.PollingTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPollingTriggerAdapter() {
		if (pollingTriggerItemProvider == null) {
			pollingTriggerItemProvider = new PollingTriggerItemProvider(this);
		}

		return pollingTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.CronTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CronTriggerItemProvider cronTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.CronTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCronTriggerAdapter() {
		if (cronTriggerItemProvider == null) {
			cronTriggerItemProvider = new CronTriggerItemProvider(this);
		}

		return cronTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.RemoteTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RemoteTriggerItemProvider remoteTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.RemoteTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRemoteTriggerAdapter() {
		if (remoteTriggerItemProvider == null) {
			remoteTriggerItemProvider = new RemoteTriggerItemProvider(this);
		}

		return remoteTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.AfterDeploymentTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AfterDeploymentTriggerItemProvider afterDeploymentTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.AfterDeploymentTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAfterDeploymentTriggerAdapter() {
		if (afterDeploymentTriggerItemProvider == null) {
			afterDeploymentTriggerItemProvider = new AfterDeploymentTriggerItemProvider(this);
		}

		return afterDeploymentTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BuildSuccessTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuildSuccessTriggerItemProvider buildSuccessTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BuildSuccessTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBuildSuccessTriggerAdapter() {
		if (buildSuccessTriggerItemProvider == null) {
			buildSuccessTriggerItemProvider = new BuildSuccessTriggerItemProvider(this);
		}

		return buildSuccessTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.StageSuccessTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StageSuccessTriggerItemProvider stageSuccessTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.StageSuccessTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStageSuccessTriggerAdapter() {
		if (stageSuccessTriggerItemProvider == null) {
			stageSuccessTriggerItemProvider = new StageSuccessTriggerItemProvider(this);
		}

		return stageSuccessTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.EnvironmentSuccessTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentSuccessTriggerItemProvider environmentSuccessTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.EnvironmentSuccessTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvironmentSuccessTriggerAdapter() {
		if (environmentSuccessTriggerItemProvider == null) {
			environmentSuccessTriggerItemProvider = new EnvironmentSuccessTriggerItemProvider(this);
		}

		return environmentSuccessTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.ScheduledDeploymentTrigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScheduledDeploymentTriggerItemProvider scheduledDeploymentTriggerItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.ScheduledDeploymentTrigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScheduledDeploymentTriggerAdapter() {
		if (scheduledDeploymentTriggerItemProvider == null) {
			scheduledDeploymentTriggerItemProvider = new ScheduledDeploymentTriggerItemProvider(this);
		}

		return scheduledDeploymentTriggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.GreenPlanCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreenPlanConditionItemProvider greenPlanConditionItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.GreenPlanCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreenPlanConditionAdapter() {
		if (greenPlanConditionItemProvider == null) {
			greenPlanConditionItemProvider = new GreenPlanConditionItemProvider(this);
		}

		return greenPlanConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.AllOtherCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllOtherConditionItemProvider allOtherConditionItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.AllOtherCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllOtherConditionAdapter() {
		if (allOtherConditionItemProvider == null) {
			allOtherConditionItemProvider = new AllOtherConditionItemProvider(this);
		}

		return allOtherConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.LinkedRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkedRepositoryItemProvider linkedRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.LinkedRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkedRepositoryAdapter() {
		if (linkedRepositoryItemProvider == null) {
			linkedRepositoryItemProvider = new LinkedRepositoryItemProvider(this);
		}

		return linkedRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.GitRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GitRepositoryItemProvider gitRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.GitRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGitRepositoryAdapter() {
		if (gitRepositoryItemProvider == null) {
			gitRepositoryItemProvider = new GitRepositoryItemProvider(this);
		}

		return gitRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BitbucketCloudRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BitbucketCloudRepositoryItemProvider bitbucketCloudRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BitbucketCloudRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBitbucketCloudRepositoryAdapter() {
		if (bitbucketCloudRepositoryItemProvider == null) {
			bitbucketCloudRepositoryItemProvider = new BitbucketCloudRepositoryItemProvider(this);
		}

		return bitbucketCloudRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BitbucketServerRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BitbucketServerRepositoryItemProvider bitbucketServerRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BitbucketServerRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBitbucketServerRepositoryAdapter() {
		if (bitbucketServerRepositoryItemProvider == null) {
			bitbucketServerRepositoryItemProvider = new BitbucketServerRepositoryItemProvider(this);
		}

		return bitbucketServerRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.GithubRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GithubRepositoryItemProvider githubRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.GithubRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGithubRepositoryAdapter() {
		if (githubRepositoryItemProvider == null) {
			githubRepositoryItemProvider = new GithubRepositoryItemProvider(this);
		}

		return githubRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.AnyVcsRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnyVcsRepositoryItemProvider anyVcsRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.AnyVcsRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnyVcsRepositoryAdapter() {
		if (anyVcsRepositoryItemProvider == null) {
			anyVcsRepositoryItemProvider = new AnyVcsRepositoryItemProvider(this);
		}

		return anyVcsRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.ChangeDetection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeDetectionItemProvider changeDetectionItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.ChangeDetection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeDetectionAdapter() {
		if (changeDetectionItemProvider == null) {
			changeDetectionItemProvider = new ChangeDetectionItemProvider(this);
		}

		return changeDetectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.QuietPeriod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuietPeriodItemProvider quietPeriodItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.QuietPeriod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuietPeriodAdapter() {
		if (quietPeriodItemProvider == null) {
			quietPeriodItemProvider = new QuietPeriodItemProvider(this);
		}

		return quietPeriodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Artifact} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArtifactItemProvider artifactItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Artifact}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArtifactAdapter() {
		if (artifactItemProvider == null) {
			artifactItemProvider = new ArtifactItemProvider(this);
		}

		return artifactItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.ArtifactSubscription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArtifactSubscriptionItemProvider artifactSubscriptionItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.ArtifactSubscription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArtifactSubscriptionAdapter() {
		if (artifactSubscriptionItemProvider == null) {
			artifactSubscriptionItemProvider = new ArtifactSubscriptionItemProvider(this);
		}

		return artifactSubscriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Requirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementItemProvider requirementItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Requirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementAdapter() {
		if (requirementItemProvider == null) {
			requirementItemProvider = new RequirementItemProvider(this);
		}

		return requirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableAssignmentItemProvider variableAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableAssignmentAdapter() {
		if (variableAssignmentItemProvider == null) {
			variableAssignmentItemProvider = new VariableAssignmentItemProvider(this);
		}

		return variableAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Label} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LabelItemProvider labelItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Label}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLabelAdapter() {
		if (labelItemProvider == null) {
			labelItemProvider = new LabelItemProvider(this);
		}

		return labelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Notification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotificationItemProvider notificationItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Notification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotificationAdapter() {
		if (notificationItemProvider == null) {
			notificationItemProvider = new NotificationItemProvider(this);
		}

		return notificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.UserRecipient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserRecipientItemProvider userRecipientItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.UserRecipient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserRecipientAdapter() {
		if (userRecipientItemProvider == null) {
			userRecipientItemProvider = new UserRecipientItemProvider(this);
		}

		return userRecipientItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.GroupRecipient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GroupRecipientItemProvider groupRecipientItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.GroupRecipient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGroupRecipientAdapter() {
		if (groupRecipientItemProvider == null) {
			groupRecipientItemProvider = new GroupRecipientItemProvider(this);
		}

		return groupRecipientItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.EmailRecipient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmailRecipientItemProvider emailRecipientItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.EmailRecipient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmailRecipientAdapter() {
		if (emailRecipientItemProvider == null) {
			emailRecipientItemProvider = new EmailRecipientItemProvider(this);
		}

		return emailRecipientItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.RoleRecipient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleRecipientItemProvider roleRecipientItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.RoleRecipient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleRecipientAdapter() {
		if (roleRecipientItemProvider == null) {
			roleRecipientItemProvider = new RoleRecipientItemProvider(this);
		}

		return roleRecipientItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.WebhookRecipient} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WebhookRecipientItemProvider webhookRecipientItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.WebhookRecipient}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWebhookRecipientAdapter() {
		if (webhookRecipientItemProvider == null) {
			webhookRecipientItemProvider = new WebhookRecipientItemProvider(this);
		}

		return webhookRecipientItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.NotificationEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotificationEventItemProvider notificationEventItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.NotificationEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotificationEventAdapter() {
		if (notificationEventItemProvider == null) {
			notificationEventItemProvider = new NotificationEventItemProvider(this);
		}

		return notificationEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BranchManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BranchManagementItemProvider branchManagementItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BranchManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBranchManagementAdapter() {
		if (branchManagementItemProvider == null) {
			branchManagementItemProvider = new BranchManagementItemProvider(this);
		}

		return branchManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BranchDelete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BranchDeleteItemProvider branchDeleteItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BranchDelete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBranchDeleteAdapter() {
		if (branchDeleteItemProvider == null) {
			branchDeleteItemProvider = new BranchDeleteItemProvider(this);
		}

		return branchDeleteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BranchIntegration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BranchIntegrationItemProvider branchIntegrationItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BranchIntegration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBranchIntegrationAdapter() {
		if (branchIntegrationItemProvider == null) {
			branchIntegrationItemProvider = new BranchIntegrationItemProvider(this);
		}

		return branchIntegrationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BranchOverride} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BranchOverrideItemProvider branchOverrideItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BranchOverride}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBranchOverrideAdapter() {
		if (branchOverrideItemProvider == null) {
			branchOverrideItemProvider = new BranchOverrideItemProvider(this);
		}

		return branchOverrideItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.BranchSpecificConfig} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BranchSpecificConfigItemProvider branchSpecificConfigItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.BranchSpecificConfig}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBranchSpecificConfigAdapter() {
		if (branchSpecificConfigItemProvider == null) {
			branchSpecificConfigItemProvider = new BranchSpecificConfigItemProvider(this);
		}

		return branchSpecificConfigItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Dependencies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependenciesItemProvider dependenciesItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Dependencies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependenciesAdapter() {
		if (dependenciesItemProvider == null) {
			dependenciesItemProvider = new DependenciesItemProvider(this);
		}

		return dependenciesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.DockerConfig} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DockerConfigItemProvider dockerConfigItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.DockerConfig}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDockerConfigAdapter() {
		if (dockerConfigItemProvider == null) {
			dockerConfigItemProvider = new DockerConfigItemProvider(this);
		}

		return dockerConfigItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.OtherConfig} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OtherConfigItemProvider otherConfigItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.OtherConfig}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOtherConfigAdapter() {
		if (otherConfigItemProvider == null) {
			otherConfigItemProvider = new OtherConfigItemProvider(this);
		}

		return otherConfigItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.DeploymentProject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentProjectItemProvider deploymentProjectItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.DeploymentProject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentProjectAdapter() {
		if (deploymentProjectItemProvider == null) {
			deploymentProjectItemProvider = new DeploymentProjectItemProvider(this);
		}

		return deploymentProjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.ReleaseNaming} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReleaseNamingItemProvider releaseNamingItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.ReleaseNaming}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReleaseNamingAdapter() {
		if (releaseNamingItemProvider == null) {
			releaseNamingItemProvider = new ReleaseNamingItemProvider(this);
		}

		return releaseNamingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.Environment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentItemProvider environmentItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.Environment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvironmentAdapter() {
		if (environmentItemProvider == null) {
			environmentItemProvider = new EnvironmentItemProvider(this);
		}

		return environmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.PlanPermissionEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlanPermissionEntryItemProvider planPermissionEntryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.PlanPermissionEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlanPermissionEntryAdapter() {
		if (planPermissionEntryItemProvider == null) {
			planPermissionEntryItemProvider = new PlanPermissionEntryItemProvider(this);
		}

		return planPermissionEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.DeploymentPermissionEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentPermissionEntryItemProvider deploymentPermissionEntryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.DeploymentPermissionEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentPermissionEntryAdapter() {
		if (deploymentPermissionEntryItemProvider == null) {
			deploymentPermissionEntryItemProvider = new DeploymentPermissionEntryItemProvider(this);
		}

		return deploymentPermissionEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.EnvironmentPermissionEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentPermissionEntryItemProvider environmentPermissionEntryItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.EnvironmentPermissionEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvironmentPermissionEntryAdapter() {
		if (environmentPermissionEntryItemProvider == null) {
			environmentPermissionEntryItemProvider = new EnvironmentPermissionEntryItemProvider(this);
		}

		return environmentPermissionEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.mddoai.metamodel.bambooMM.NamedEnvironmentPermission} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedEnvironmentPermissionItemProvider namedEnvironmentPermissionItemProvider;

	/**
	 * This creates an adapter for a {@link com.mddoai.metamodel.bambooMM.NamedEnvironmentPermission}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedEnvironmentPermissionAdapter() {
		if (namedEnvironmentPermissionItemProvider == null) {
			namedEnvironmentPermissionItemProvider = new NamedEnvironmentPermissionItemProvider(this);
		}

		return namedEnvironmentPermissionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (planItemProvider != null)
			planItemProvider.dispose();
		if (stageItemProvider != null)
			stageItemProvider.dispose();
		if (jobItemProvider != null)
			jobItemProvider.dispose();
		if (scriptTaskItemProvider != null)
			scriptTaskItemProvider.dispose();
		if (cleanTaskItemProvider != null)
			cleanTaskItemProvider.dispose();
		if (checkoutTaskItemProvider != null)
			checkoutTaskItemProvider.dispose();
		if (mavenTaskItemProvider != null)
			mavenTaskItemProvider.dispose();
		if (injectVariablesTaskItemProvider != null)
			injectVariablesTaskItemProvider.dispose();
		if (testParserTaskItemProvider != null)
			testParserTaskItemProvider.dispose();
		if (artifactDownloadTaskItemProvider != null)
			artifactDownloadTaskItemProvider.dispose();
		if (artifactDownloadItemItemProvider != null)
			artifactDownloadItemItemProvider.dispose();
		if (anyTaskItemProvider != null)
			anyTaskItemProvider.dispose();
		if (taskConditionItemProvider != null)
			taskConditionItemProvider.dispose();
		if (pollingTriggerItemProvider != null)
			pollingTriggerItemProvider.dispose();
		if (cronTriggerItemProvider != null)
			cronTriggerItemProvider.dispose();
		if (remoteTriggerItemProvider != null)
			remoteTriggerItemProvider.dispose();
		if (afterDeploymentTriggerItemProvider != null)
			afterDeploymentTriggerItemProvider.dispose();
		if (buildSuccessTriggerItemProvider != null)
			buildSuccessTriggerItemProvider.dispose();
		if (stageSuccessTriggerItemProvider != null)
			stageSuccessTriggerItemProvider.dispose();
		if (environmentSuccessTriggerItemProvider != null)
			environmentSuccessTriggerItemProvider.dispose();
		if (scheduledDeploymentTriggerItemProvider != null)
			scheduledDeploymentTriggerItemProvider.dispose();
		if (greenPlanConditionItemProvider != null)
			greenPlanConditionItemProvider.dispose();
		if (allOtherConditionItemProvider != null)
			allOtherConditionItemProvider.dispose();
		if (linkedRepositoryItemProvider != null)
			linkedRepositoryItemProvider.dispose();
		if (gitRepositoryItemProvider != null)
			gitRepositoryItemProvider.dispose();
		if (bitbucketCloudRepositoryItemProvider != null)
			bitbucketCloudRepositoryItemProvider.dispose();
		if (bitbucketServerRepositoryItemProvider != null)
			bitbucketServerRepositoryItemProvider.dispose();
		if (githubRepositoryItemProvider != null)
			githubRepositoryItemProvider.dispose();
		if (anyVcsRepositoryItemProvider != null)
			anyVcsRepositoryItemProvider.dispose();
		if (changeDetectionItemProvider != null)
			changeDetectionItemProvider.dispose();
		if (quietPeriodItemProvider != null)
			quietPeriodItemProvider.dispose();
		if (artifactItemProvider != null)
			artifactItemProvider.dispose();
		if (artifactSubscriptionItemProvider != null)
			artifactSubscriptionItemProvider.dispose();
		if (requirementItemProvider != null)
			requirementItemProvider.dispose();
		if (variableAssignmentItemProvider != null)
			variableAssignmentItemProvider.dispose();
		if (labelItemProvider != null)
			labelItemProvider.dispose();
		if (notificationItemProvider != null)
			notificationItemProvider.dispose();
		if (userRecipientItemProvider != null)
			userRecipientItemProvider.dispose();
		if (groupRecipientItemProvider != null)
			groupRecipientItemProvider.dispose();
		if (emailRecipientItemProvider != null)
			emailRecipientItemProvider.dispose();
		if (roleRecipientItemProvider != null)
			roleRecipientItemProvider.dispose();
		if (webhookRecipientItemProvider != null)
			webhookRecipientItemProvider.dispose();
		if (notificationEventItemProvider != null)
			notificationEventItemProvider.dispose();
		if (branchManagementItemProvider != null)
			branchManagementItemProvider.dispose();
		if (branchDeleteItemProvider != null)
			branchDeleteItemProvider.dispose();
		if (branchIntegrationItemProvider != null)
			branchIntegrationItemProvider.dispose();
		if (branchOverrideItemProvider != null)
			branchOverrideItemProvider.dispose();
		if (branchSpecificConfigItemProvider != null)
			branchSpecificConfigItemProvider.dispose();
		if (dependenciesItemProvider != null)
			dependenciesItemProvider.dispose();
		if (dockerConfigItemProvider != null)
			dockerConfigItemProvider.dispose();
		if (otherConfigItemProvider != null)
			otherConfigItemProvider.dispose();
		if (deploymentProjectItemProvider != null)
			deploymentProjectItemProvider.dispose();
		if (releaseNamingItemProvider != null)
			releaseNamingItemProvider.dispose();
		if (environmentItemProvider != null)
			environmentItemProvider.dispose();
		if (planPermissionEntryItemProvider != null)
			planPermissionEntryItemProvider.dispose();
		if (deploymentPermissionEntryItemProvider != null)
			deploymentPermissionEntryItemProvider.dispose();
		if (environmentPermissionEntryItemProvider != null)
			environmentPermissionEntryItemProvider.dispose();
		if (namedEnvironmentPermissionItemProvider != null)
			namedEnvironmentPermissionItemProvider.dispose();
	}

}
