/**
 *
 * $Id$
 */
package com.mddoai.metamodel.swarch.validation;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.swarch.SoftwareArchitecture}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SoftwareArchitectureValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateType(String value);

	boolean validateBuild_system(String value);

	boolean validateLanguage(String value);

	boolean validateUnit_test(String value);

	boolean validateHealth_check(String value);

	boolean validateLint_check(String value);
}
