/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.Expression;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.Artifact}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArtifactValidator {
	boolean validate();

	boolean validateArtifactName(Expression value);

	boolean validateIncludePaths(EList<Expression> value);

	boolean validateExcludePaths(EList<Expression> value);

	boolean validateRetentionTime(Expression value);

	boolean validateStore(boolean value);
}
