/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.CACHE_MODE;
import com.mddoai.metamodel.pim.pimMM.Expression;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.Cache}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CacheValidator {
	boolean validate();

	boolean validateCacheName(Expression value);

	boolean validateKeys(EList<Expression> value);

	boolean validatePaths(EList<Expression> value);

	boolean validateStore(CACHE_MODE value);
}
