/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.Expression;
import com.mddoai.metamodel.pim.pimMM.Step;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.ConditionalStep}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionalStepValidator {
	boolean validate();

	boolean validateIfCondition(Expression value);

	boolean validateThenRun(EList<Step> value);

	boolean validateElseRun(EList<Step> value);
}
