/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.Expression;
import com.mddoai.metamodel.pim.pimMM.VariableDeclaration;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.DockerContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DockerContainerValidator {
	boolean validate();

	boolean validateLabel(String value);

	boolean validateImage(Expression value);

	boolean validateEnvironmentVariables(EMap<VariableDeclaration, Expression> value);

	boolean validateVolumes(EList<Expression> value);

	boolean validatePorts(EList<Expression> value);

	boolean validateOptions(String value);

	boolean validateRegistryUsername(Expression value);

	boolean validateRegistryPassword(Expression value);

	boolean validateNetwork(Expression value);
}
