/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.EQUALITY_OPS;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.EqualityOp}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EqualityOpValidator {
	boolean validate();

	boolean validateOp(EQUALITY_OPS value);
}
