/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.DockerContainer;
import com.mddoai.metamodel.pim.pimMM.Expression;
import com.mddoai.metamodel.pim.pimMM.Job;
import com.mddoai.metamodel.pim.pimMM.Matrix;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.Job}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JobValidator {
	boolean validate();

	boolean validateId(String value);

	boolean validateIfCondition(Expression value);

	boolean validateServices(EList<DockerContainer> value);

	boolean validateMatrix(Matrix value);

	boolean validatePrevious(EList<Job> value);

	boolean validateNext(EList<Job> value);

	boolean validateMaxAttempts(Integer value);

	boolean validateAllowFailure(Boolean value);
}
