/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.Expression;
import com.mddoai.metamodel.pim.pimMM.VariableDeclaration;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.NonConditionalStep}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NonConditionalStepValidator {
	boolean validate();

	boolean validateId(String value);

	boolean validateName(String value);

	boolean validateEnvironmentVariables(EMap<VariableDeclaration, Expression> value);

	boolean validateAllowFailure(Boolean value);

	boolean validateWorkingDirectory(Expression value);

	boolean validateTimeoutMinutes(Expression value);
}
