/**
 *
 * $Id$
 */
package com.mddoai.metamodel.pim.pimMM.validation;

import com.mddoai.metamodel.pim.pimMM.Agent;
import com.mddoai.metamodel.pim.pimMM.Expression;
import com.mddoai.metamodel.pim.pimMM.Input;
import com.mddoai.metamodel.pim.pimMM.Output;
import com.mddoai.metamodel.pim.pimMM.VariableDeclaration;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.mddoai.metamodel.pim.pimMM.PipelineBlock}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PipelineBlockValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateAgent(Agent value);

	boolean validateInputs(EList<Input> value);

	boolean validateOutputs(EList<Output> value);

	boolean validateEnvironmentVariables(EMap<VariableDeclaration, Expression> value);

	boolean validateTimeoutMinutes(Integer value);

	boolean validateWorkingDirectory(Expression value);

	boolean validateShell(Expression value);
}
